const MARDEK = {
	Chapter1: {
		Image: "Chapter1",
		Mardek: {
			Image:"kidMardek",
			Name:"KidMardek",
			Skills:[
				{Type: "Imagination", Name: "Strike", Found: "Stick", Mastered: false},
				{Type: "Imagination", Name: "Huff-Puff", Found: "Tunic", Mastered: false},
				{Type: "PhysAtk", Name: "DMG+1", Found: "Stick", Mastered: false},
				{Type: "PhysDef", Name: "Block", Found: "Stick", Mastered: false},
				{Type: "Passive", Name: "Insomnia", Found: "Cog necklace (reaction doesn't cary over to CH2)", Mastered: false}
			]
		},
		Deugan: {
			Image:"kidDeugan",
			Name:"KidDeugan",
			Skills:[
				{Type: "Imagination", Name: "Strike", Found: "Big Stick", Mastered: false},
				{Type: "Imagination", Name: "Huff-Puff", Found: "Tunic", Mastered: false},
				{Type: "PhysAtk", Name: "DMG+1", Found: "Big Stick", Mastered: false},
				{Type: "PhysDef", Name: "Block", Found: "Big Stick", Mastered: false},
				{Type: "Passive", Name: "Insomnia", Found: "Cog necklace (reaction doesn't cary over to CH2)",  Mastered: false}
			]
		}
	},
	Chapter2: {
		Image: "Chapter2",
        Mardek: {
			Image:"guardMardek",
			Name:"Mardek",
			Skills:[
				{Type: "MagicSword", Name: "Heal", Found: "Starting Skill", Mastered: true},
				{Type: "MagicSword", Name: "Remove Taint", Found: "Snakestone", Mastered: false},
				{Type: "MagicSword", Name: "Shield", Found: "MoonstoneRing", Mastered: false},
				{Type: "MagicSword", Name: "M. Shield", Found: "Lapis Lily", Mastered: false},
				{Type: "MagicSword", Name: "Warp", Found: "Starting Skill", Mastered: true},
				{Type: "PhysAtk",  Name: "DMG+10%", Found: "Iron Sword, Mace", Mastered: false},
				{Type: "PhysAtk",  Name: "DMG+20%", Found: "Longsword", Mastered: false},
				{Type: "PhysAtk",  Name: "DMG+30%", Found: "Champion Sword", Mastered: false},
				{Type: "PhysAtk",  Name: "Quarry: UNDEAD", Found: "Silver Sword", Mastered: false},
				{Type: "PhysAtk",  Name: "Degeneration", Found: "ShadowBlade", Mastered: false},
				{Type: "PhysDef",  Name: "DMG-10%", Found: "Wooden Shield, Green Chainmail", Mastered: false},
				{Type: "PhysDef",  Name:  "DMG-20%", Found: "Chainmail, Copper Breastplate", Mastered: false},
				{Type: "PhysDef",  Name:  "DMG Soak 10", Found: "Bronze Shield, Pickaxe Pendant", Mastered: false},
				{Type: "PhysDef",  Name:  "DMG Soak 20", Found: "Breastplate", Mastered: false},
				{Type: "PhysDef",  Name:  "Evasion 20%", Found: "Bandit Leather", Mastered: false},
				{Type: "MagDef",  Name:  "M DMG-10%", Found: "Green Chainmail", Mastered: false},
				{Type: "MagDef",  Name:  "M FIRE-50%", Found: "FirePendant", Mastered: false},
				{Type: "Passive",  Name:  "HP+10%", Found: "Body Crystal", Mastered: false},
				{Type: "Passive",  Name:  "MP+10%", Found: "Lapis Lily, Mind Crystal", Mastered: false},
				{Type: "Passive",  Name:  "Antibody", Found: "Snakestone", Mastered: false},
				{Type: "Passive",  Name:  "Insomnia", Found: "Cog Necklace, MoonstoneRing", Mastered: false},
				{Type: "Passive",  Name:  "Locomotion", Found: "Belt of Movement", Mastered: false},
				{Type: "Passive",  Name:  "Bright Eyes", Found: "OnyxRing", Mastered: false},
				{Type: "Passive",  Name:  "Purity", Found: "Bonemail", Mastered: false},
				{Type: "Passive",  Name:  "Vim", Found: "Bonestone", Mastered: false},
				{Type: "Passive",  Name:  "AGL+1", Found: "Bandit Leather", Mastered: false},
				{Type: "Passive",  Name:  "Resist WATER", Found: "Trilobite Armour", Mastered: false},
				{Type: "Passive",  Name:  "Resist EARTH", Found: "GeoJacket", Mastered: false}
			]
		},
		Deugan: {
			Image:"Deugan",
			Name:"Deugan",
			Skills:[
				{Type: "Spellbladery", Name: "Power Attack", Found: "Greatsword, Mythril Greatblade", Mastered: false},
				{Type: "Spellbladery", Name: "Earth Slash", Found: "Tectonic Sword", Mastered: false},
				{Type: "Spellbladery", Name: "Boost", Found: "Burial Sword", Mastered: false},
				{Type: "Spellbladery", Name: "Barrier Break", Found: "Iron Greatblade", Mastered: false},
				{Type: "Spellbladery", Name: "Spiritblade", Found: "Ancient Sword", Mastered: false},
				{Type: "PhysAtk", Name: "DMG+20%", Found: "Greatsword", Mastered: false},
				{Type: "PhysAtk", Name: "DMG+30%", Found: "Burial Sword", Mastered: false},
				{Type: "PhysDef", Name: "DMG-10%", Found: "Green Chainmail", Mastered: false},
				{Type: "PhysDef", Name: "DMG-20%", Found: "Chainmail, Copper Breastplate", Mastered: false},
				{Type: "PhysDef", Name: "DMG Soak 10", Found: "Pickaxe Pendant", Mastered: false},
				{Type: "PhysDef", Name: "DMG Soak 20", Found: "Breastplate", Mastered: false},
				{Type: "PhysDef", Name: "Evasion 20%", Found: "Bandit Leather", Mastered: false},
				{Type: "MagDef", Name: "M DMG-10%", Found: "Green Chainmail", Mastered: false},
				{Type: "MagDef", Name: "M DMG-20%", Found: "Ancient Sword", Mastered: false},
				{Type: "MagDef", Name: "M FIRE-50%", Found: "FirePendant", Mastered: false},
				{Type: "Passive", Name: "HP+10%", Found: "Body Crystal", Mastered: false},
				{Type: "Passive", Name: "MP+10%", Found: "Lapis Lily, Mind Crystal", Mastered: false},
				{Type: "Passive", Name: "Antibody", Found: "Snakestone", Mastered: false},
				{Type: "Passive", Name: "Insomnia", Found: "Cog Necklace, MoonstoneRing", Mastered: false},
				{Type: "Passive", Name: "Locomotion", Found: "Belt of Movement", Mastered: false},
				{Type: "Passive", Name: "Bright Eyes", Found: "OnyxRing", Mastered: false},
				{Type: "Passive", Name: "Purity", Found: "Bonemail", Mastered: false},
				{Type: "Passive", Name: "Vim", Found: "Bonestone", Mastered: false},
				{Type: "Passive", Name: "AGL+1", Found: "Bandit Leather", Mastered: false},
				{Type: "Passive", Name: "Resist WATER", Found: "Trilobite Armour", Mastered: false},
				{Type: "Passive", Name: "Resist EARTH", Found: "GeoJacket", Mastered: false}
			]
		},
		Emela: {
			Image:"Emela",
			Name:"Emela",
			Skills:[
				{Type: "Elemancy", Name: "Flame", Found: "Fire Rod", Mastered: false},
				{Type: "Elemancy", Name: "Lightning Bolt", Found: "Starting Skill", Mastered: true},
				{Type: "Elemancy", Name: "Stonesplosion", Found: "Earth Rod", Mastered: false},
				{Type: "Elemancy", Name: "Bubble", Found: "Water Rod", Mastered: false},
				{Type: "Elemancy", Name: "Aqualung", Found: "Starting Skill", Mastered: true},
				{Type: "PhysDef", Name: "DMG-10%", Found: "Wooden Shield", Mastered: false},
				{Type: "PhysDef", Name: "DMG-20%", Found: "Starting Skill", Mastered: true},
				{Type: "PhysDef", Name: "DMG Soak 10", Found: "Bronze Shield, Pickaxe Pendant", Mastered: false},
				{Type: "PhysDef", Name: "DMG Soak 20", Found: "Spiked Hide Armour", Mastered: false},
				{Type: "PhysDef", Name: "Evasion 20%", Found: "Bandit Leather", Mastered: false},
				{Type: "MagAtk", Name: "M DMG+10%", Found: "Lightning Rod", Mastered: false},
				{Type: "MagAtk", Name: "M DMG+20%", Found: "Water Rod", Mastered: false},
				{Type: "MagAtk", Name: "M+Poison 20%", Found: "Earth Rod", Mastered: false},
				{Type: "MagAtk", Name: "M+Stun 20%", Found: "Lightning Rod", Mastered: false},
				{Type: "MagDef", Name: "M DMG-10%", Found: "Mage Robe", Mastered: false},
				{Type: "MagDef", Name: "M DMG-20%", Found: "Hempen Robe", Mastered: false},
				{Type: "MagDef", Name: "M DMG-30%", Found: "Green Robe", Mastered: false},
				{Type: "MagDef", Name: "M FIRE-50%", Found: "FirePendant", Mastered: false},
				{Type: "Passive", Name: "HP+10%", Found: "Body Crystal", Mastered: false},
				{Type: "Passive", Name: "MP+10%", Found: "Lapis Lily, Mind Crystal", Mastered: false},
				{Type: "Passive", Name: "Antibody", Found: "Snakestone", Mastered: false},
				{Type: "Passive", Name: "Insomnia", Found: "Cog Necklace, MoonstoneRing", Mastered: false},
				{Type: "Passive", Name: "Locomotion", Found: "Belt of Movement", Mastered: false},
				{Type: "Passive", Name: "Bright Eyes", Found: "OnyxRing", Mastered: false},
				{Type: "Passive", Name: "Vim", Found: "Bonestone", Mastered: false},
				{Type: "Passive", Name: "AGL+1", Found: "Bandit Leather", Mastered: false},
				{Type: "Passive", Name: "Resist EARTH", Found: "GeoJacket", Mastered: false}
			]
		},
		Vehrn: {
			Image:"Vehrn",
			Name:"Vehrn",
			Skills:[
				{Type: "HolyArts", Name: "Smite Evil", Found: "Bronze Sword", Mastered: false},
				{Type: "HolyArts", Name: "Disrupt Undead", Found: "Silver Sword", Mastered: false},
				{Type: "HolyArts", Name: "Green Lightning", Found: "YalortianAmulet", Mastered: false},
				{Type: "PhysAtk", Name: "Smite+", Found: "Bronze Sword", Mastered: false},
				{Type: "PhysAtk", Name: "DMG+10%", Found: "Iron Sword, Mace", Mastered: false},
				{Type: "PhysAtk", Name: "DMG+20%", Found: "Longsword", Mastered: false},
				{Type: "PhysAtk", Name: "DMG+30%", Found: "Champion Sword", Mastered: false},
				{Type: "PhysAtk", Name: "Quarry: UNDEAD", Found: "Silver Sword", Mastered: false},
				{Type: "PhysAtk", Name: "Degeneration", Found: "ShadowBlade", Mastered: false},
				{Type: "PhysDef", Name: "DMG-10%", Found: "Wooden Shield, Green Chainmail", Mastered: false},
				{Type: "PhysDef", Name: "DMG-20%", Found: "Chainmail, Copper Breastplate", Mastered: false},
				{Type: "PhysDef", Name: "DMG Soak 10", Found: "Bronze Shield, Pickaxe Pendant", Mastered: false},
				{Type: "PhysDef", Name: "DMG Soak 20", Found: "Breastplate", Mastered: false},
				{Type: "PhysDef", Name: "Evasion 20%", Found: "Bandit Leather", Mastered: false},
				{Type: "MagDef", Name: "M DMG-10%", Found: "Green Chainmail", Mastered: false},
				{Type: "MagDef", Name: "M FIRE-50%", Found: "FirePendant", Mastered: false},
				{Type: "Passive", Name: "HP+10%", Found: "Body Crystal", Mastered: false},
				{Type: "Passive", Name: "MP+10%", Found: "Lapis Lily, Mind Crystal", Mastered: false},
				{Type: "Passive", Name: "Antibody", Found: "Snakestone", Mastered: false},
				{Type: "Passive", Name: "Insomnia", Found: "Cog Necklace, MoonstoneRing", Mastered: false},
				{Type: "Passive", Name: "Locomotion", Found: "Belt of Movement", Mastered: false},
				{Type: "Passive", Name: "Bright Eyes", Found: "OnyxRing", Mastered: false},
				{Type: "Passive", Name: "Purity", Found: "Bonemail", Mastered: false},
				{Type: "Passive", Name: "Vim", Found: "Bonestone", Mastered: false},
				{Type: "Passive", Name: "AGL+1", Found: "Bandit Leather", Mastered: false},
				{Type: "Passive", Name: "Resist WATER", Found: "Trilobite Armour", Mastered: false},
				{Type: "Passive", Name: "Resist EARTH", Found: "GeoJacket", Mastered: false}
			]
		},
		Zach: {
			Image:"Zach",
			Name:"Zach",
			Skills:[
				{Type: "Techniques", Name: "Berserk", Found: "Shashiik", Mastered: false},
				{Type: "Techniques", Name: "Crescendo Slash", Found: "Boneslicer", Mastered: false},
				{Type: "Techniques", Name: "Sure Slash", Found: "Twin Trilobites", Mastered: false},
				{Type: "PhysAtk", Name: "DMG+20%", Found: "Shashiik", Mastered: false},
				{Type: "PhysAtk", Name: "Soulstrike", Found: "Shashiik", Mastered: false},
				{Type: "PhysAtk", Name: "Quarry: UNDEAD", Found: "Boneslicer", Mastered: false},
				{Type: "PhysAtk", Name: "Quarry: INSECT", Found: "Twin Trilobites", Mastered: false},
				{Type: "PhysDef", Name: "DMG-10%", Found: "Green Chainmail", Mastered: false},
				{Type: "PhysDef", Name: "DMG-20%", Found: "Chainmail, Copper Breastplate", Mastered: false},
				{Type: "PhysDef", Name: "DMG Soak 10", Found: "Pickaxe Pendant", Mastered: false},
				{Type: "PhysDef", Name: "DMG Soak 20", Found: "Breastplate", Mastered: false},
				{Type: "PhysDef", Name: "Evasion 20%", Found: "Bandit Leather", Mastered: false},
				{Type: "MagDef", Name: "M DMG-10%", Found: "Green Chainmail", Mastered: false},
				{Type: "MagDef", Name: "M FIRE-50%", Found: "FirePendant", Mastered: false},
				{Type: "Passive", Name: "HP+10%", Found: "Body Crystal", Mastered: false},
				{Type: "Passive", Name: "MP+10%", Found: "Lapis Lily, Mind Crystal", Mastered: false},
				{Type: "Passive", Name: "Antibody", Found: "Snakestone", Mastered: false},
				{Type: "Passive", Name: "Insomnia", Found: "Cog Necklace, MoonstoneRing", Mastered: false},
				{Type: "Passive", Name: "Locomotion", Found: "Belt of Movement", Mastered: false},
				{Type: "Passive", Name: "Bright Eyes", Found: "OnyxRing", Mastered: false},
				{Type: "Passive", Name: "Purity", Found: "Bonemail", Mastered: false},
				{Type: "Passive", Name: "Vim", Found: "Bonestone", Mastered: false},
				{Type: "Passive", Name: "AGL+1", Found: "Bandit Leather", Mastered: false},
				{Type: "Passive", Name: "Resist WATER", Found: "Trilobite Armour", Mastered: false},
				{Type: "Passive", Name: "Resist EARTH", Found: "GeoJacket", Mastered: false}
			]
		}
	},
    Chapter3: {
		Image: "Chapter3",
		Mardek: {
			Image:"knightMardek",
			Name:"Mardek",
			Skills:[
				{Type: "MagicSword", Name: "Heal", Found: "Starting Skill", Mastered: true},
				{Type: "MagicSword", Name: "Regen", Found: "Moonstone", Mastered: false},
				{Type: "MagicSword", Name: "Remove Taint", Found: "Snakestone", Mastered: false},
				{Type: "MagicSword", Name: "Remove Evil", Found: "M Charm", Mastered: false},
				{Type: "MagicSword", Name: "Shield", Found: "MoonstoneRing, Gold Shield", Mastered: false},
				{Type: "MagicSword", Name: "M. Shield", Found: "Lapis Lily, Rune Shield, Rune Shield +", Mastered: false},
				{Type: "MagicSword", Name: "Morality Block", Found: "Bronze Armour, Solakian Platemail", Mastered: false},
				{Type: "MagicSword", Name: "Fire Slash", Found: "Flametongue", Mastered: false},
				{Type: "MagicSword", Name: "Water Slash", Found: "Fishslayer", Mastered: false},
				{Type: "MagicSword", Name: "Air Slash", Found: "Aeropolitan Scimitar", Mastered: false},
				{Type: "MagicSword", Name: "Earth Slash", Found: "Forest Edge", Mastered: false},
				{Type: "MagicSword", Name: "Warp", Found: "Starting Skill", Mastered: true},
				{Type: "PhysAtk", Name: "DMG+10%", Found: "Iron Sword, Mace, Mythril Sword", Mastered: false},
				{Type: "PhysAtk", Name: "DMG+20%", Found: "Longsword, Sun Sword", Mastered: false},
				{Type: "PhysAtk", Name: "DMG+30%", Found: "Champion Sword, Champion Sword II", Mastered: false},
				{Type: "PhysAtk", Name: "Critical+20%", Found: "Xantusian Scimitar", Mastered: false},
				{Type: "PhysAtk", Name: "Accuracy+50%", Found: "Scoping Lens", Mastered: false},
				{Type: "PhysAtk", Name: "Soulstrike", Found: "Champion Sword II", Mastered: false},
				{Type: "PhysAtk", Name: "Quarry: UNDEAD", Found: "Silver Sword", Mastered: false},
				{Type: "PhysAtk", Name: "Quarry: SPIRIT", Found: "Wispstone", Mastered: false},
				{Type: "PhysAtk", Name: "Degeneration 10%", Found: "ShadowBlade, Onyx", Mastered: false},
				{Type: "PhysAtk", Name: "Drain HP 10%", Found: "Blood Sword, BloodOpal", Mastered: false},
				{Type: "PhysAtk", Name: "P+Bleed 20%", Found: "Cursed Blade", Mastered: false},
				{Type: "PhysDef", Name: "DMG-10%", Found: "Wooden Shield, Green Chainmail, SilverRing", Mastered: false},
				{Type: "PhysDef", Name: "DMG-20%", Found: "Chainmail, Copper Breastplate, Spiked Hide Armour", Mastered: false},
				{Type: "PhysDef", Name: "DMG-30%", Found: "Iron Armour, Mythril Platemail, Golden Gauntlet", Mastered: false},
				{Type: "PhysDef", Name: "DMG Soak 10", Found: "Bronze Shield, Pickaxe Pendant", Mastered: false},
				{Type: "PhysDef", Name: "DMG Soak 20", Found: "Breastplate, Gold Shield, Spiked Hide Armour", Mastered: false},
				{Type: "PhysDef", Name: "DMG Soak 30", Found: "Steel Stole, Mythril Platemail", Mastered: false},
				{Type: "PhysDef", Name: "AIR-50%", Found: "Wing Shield", Mastered: false},
				{Type: "PhysDef", Name: "LIGHT-50%", Found: "Shield of Light, Solakian Platemail", Mastered: false},
				{Type: "PhysDef", Name: "DARK-50%", Found: "Shield of Darkness", Mastered: false},
				{Type: "PhysDef", Name: "Evasion 20%", Found: "Bandit Leather, Eclipse Amulet", Mastered: false},
				{Type: "MagAtk", Name: "M DMG+10%", Found: "Scoping Lens", Mastered: false},
				{Type: "MagAtk", Name: "M DMG+20%", Found: "Feather Crest, Golden M Helm", Mastered: false},
				{Type: "MagDef", Name: "M DMG-10%", Found: "Green Chainmail, Silver Circlet", Mastered: false},
				{Type: "MagDef", Name: "M DMG-20%", Found: "Rune Shield, Turquoise Armour", Mastered: false},
				{Type: "MagDef", Name: "M DMG Soak 10", Found: "Elf Cap", Mastered: false},
				{Type: "MagDef", Name: "M DMG Soak 20", Found: "Rune Shield +", Mastered: false},
				{Type: "MagDef", Name: "M FIRE-50%", Found: "FirePendant, Dragonblood Charm", Mastered: false},
				{Type: "MagDef", Name: "M WATER-50%", Found: "WaterPendant", Mastered: false},
				{Type: "MagDef", Name: "M AIR-50%", Found: "Wing Shield, AirPendant", Mastered: false},
				{Type: "MagDef", Name: "M EARTH-50%", Found: "EarthPendant", Mastered: false},
				{Type: "MagDef", Name: "M LIGHT-50%", Found: "Shield of Light", Mastered: false},
				{Type: "MagDef", Name: "M DARK-50%", Found: "Shield of Darkness, Black Hat", Mastered: false},
				{Type: "MagDef", Name: "Spell Resist: 30%", Found: "Glyph Shield", Mastered: false},
				{Type: "Passive", Name: "HP+10%", Found: "Body Crystal", Mastered: false},
				{Type: "Passive", Name: "HP+20%", Found: "Emerald Bangle", Mastered: false},
				{Type: "Passive", Name: "MP+10%", Found: "Lapis Lily, Mind Crystal", Mastered: false},
				{Type: "Passive", Name: "MP+20%", Found: "Sapphire Bangle, SoulStone", Mastered: false},
				{Type: "Passive", Name: "Antibody", Found: "Snakestone, Snakemail, Viper's Eye", Mastered: false},
				{Type: "Passive", Name: "Loquacity", Found: "Sorcerer's Soul", Mastered: false},
				{Type: "Passive", Name: "Suppleness", Found: "Dragonblood Charm, Warlord's Soul", Mastered: false},
				{Type: "Passive", Name: "Insomnia", Found: "Cog Necklace, MoonstoneRing, Moonstone", Mastered: false},
				{Type: "Passive", Name: "Clarity", Found: "Amethyst, Amethyst Earring", Mastered: false},
				{Type: "Passive", Name: "Locomotion", Found: "Belt of Movement", Mastered: false},
				{Type: "Passive", Name: "Bright Eyes", Found: "OnyxRing, Golden M Helmet, SolakianAmulet", Mastered: false},
				{Type: "Passive", Name: "Purity", Found: "Bonemail, Solakian Platemail, Yalortian Robe", Mastered: false},
				{Type: "Passive", Name: "Vim", Found: "Bonestone", Mastered: false},
				{Type: "Passive", Name: "STR+1", Found: "FireOpal, Scarlet Stole +2", Mastered: false},
				{Type: "Passive", Name: "STR+2", Found: "Ruby, Scarlet Stole +4", Mastered: false},
				{Type: "Passive", Name: "STR+3", Found: "Scarlet Stole +6", Mastered: false},
				{Type: "Passive", Name: "VIT+1", Found: "Jade, Green Stole +2", Mastered: false},
				{Type: "Passive", Name: "VIT+2", Found: "Emerald, Green Stole +4", Mastered: false},
				{Type: "Passive", Name: "VIT+3", Found: "Green Stole +6", Mastered: false},
				{Type: "Passive", Name: "SPR+1", Found: "Aquamarine, Azure Staff +2", Mastered: false},
				{Type: "Passive", Name: "SPR+2", Found: "Sapphire, Azure Stole +4, Turquoise Armour", Mastered: false},
				{Type: "Passive", Name: "SPR+3", Found: "Azure Stole +6", Mastered: false},
				{Type: "Passive", Name: "AGL+1", Found: "Bandit Leather, Topaz", Mastered: false},
				{Type: "Passive", Name: "AGL+2", Found: "Boots of Celerity", Mastered: false},
				{Type: "Passive", Name: "Resist FIRE", Found: "Flamemail", Mastered: false},
				{Type: "Passive", Name: "Resist WATER", Found: "Trilobite Armour", Mastered: false},
				{Type: "Passive", Name: "Resist EARTH", Found: "GeoJacket", Mastered: false},
				{Type: "Passive", Name: "Resist DARK", Found: "Night Jacket", Mastered: false},
				{Type: "Passive", Name: "Resist AETHER", Found: "Astral Wanderer's Garb, Turquoise", Mastered: false},
				{Type: "Passive", Name: "Rainbow Aura Lv.1", Found: "LesserRainbowShirt, Rainbow Disc", Mastered: false},
				{Type: "Passive", Name: "SOS Regen", Found: "Kind Star", Mastered: false},
				{Type: "Passive", Name: "SOS Berserk", Found: "Horned Helm", Mastered: false},
				{Type: "Passive", Name: "EXP+20%", Found: "Candriathope", Mastered: false},
				{Type: "Passive", Name: "Double AP", Found: "EveningStar", Mastered: false},
				{Type: "Passive", Name: "Double Gold", Found: "Regal Crown", Mastered: false},
				{Type: "Passive", Name: "Loot Finder Lv.1", Found: "Lucky Coin", Mastered: false}
			]
		},
		Donovan: {
			Image:"Donovan",
			Name:"Donovan",
			Skills:[
				{Type: "Pyromancy", Name: "Flame", Found: "Ember Spear", Mastered: false},
				{Type: "Pyromancy", Name: "Blaze", Found: "Firefang", Mastered: false},
				{Type: "Pyromancy", Name: "Burn", Found: "Desert Spear", Mastered: false},
				{Type: "Pyromancy", Name: "Null Fire Once", Found: "Firestone Ring, Firefang", Mastered: false},
				{Type: "Pyromancy", Name: "Remove Numbness", Found: "Iron Spear", Mastered: false},
				{Type: "Pyromancy", Name: "Pyro Shell", Found: "Obelisk", Mastered: false},
				{Type: "Pyromancy", Name: "Strength Boost", Found: "Dragonblood Charm", Mastered: false},
				{Type: "PhysAtk", Name: "DMG+10%", Found: "Stingstick", Mastered: false},
				{Type: "PhysAtk", Name: "DMG+20%", Found: "Firefang", Mastered: false},
				{Type: "PhysAtk", Name: "Accuracy+50%", Found: "Scoping Lens", Mastered: false},
				{Type: "PhysAtk", Name: "Soulstrike", Found: "Ember Spear, Wing Spear", Mastered: false},
				{Type: "PhysAtk", Name: "Quarry: SPIRIT", Found: "Wispstone", Mastered: false},
				{Type: "PhysAtk", Name: "Degeneration 10%", Found: "Onyx", Mastered: false},
				{Type: "PhysAtk", Name: "Drain HP 10%", Found: "BloodOpal", Mastered: false},
				{Type: "PhysAtk", Name: "P+Poison 20%", Found: "Stingstick", Mastered: false},
				{Type: "PhysDef", Name: "DMG-10%", Found: "Snakemail, GoldRing Gauntlet", Mastered: false},
				{Type: "PhysDef", Name: "DMG-20%", Found: "Steel Stole, Magic Shirt, Inventing Coat", Mastered: false},
				{Type: "PhysDef", Name: "DMG-30%", Found: "Golden Gauntlet", Mastered: false},
				{Type: "PhysDef", Name: "DMG Soak 10", Found: "Pickaxe Pendant", Mastered: false},
				{Type: "PhysDef", Name: "DMG Soak 20", Found: "Spiked Hide Armour, Reinforced Leather", Mastered: false},
				{Type: "PhysDef", Name: "DMG Soak 30", Found: "Steel Stole", Mastered: false},
				{Type: "PhysDef", Name: "Evasion 20%", Found: "Bandit Leather, Eclipse Amulet", Mastered: false},
				{Type: "MagAtk", Name: "M DMG+10%", Found: "Scoping Lens", Mastered: false},
				{Type: "MagAtk", Name: "M DMG+20%", Found: "Magic Poker, Feather Crest", Mastered: false},
				{Type: "MagAtk", Name: "M FIRE+20%", Found: "Ember Spear", Mastered: false},
				{Type: "MagAtk", Name: "M AIR+20%", Found: "Wing Spear", Mastered: false},
				{Type: "MagDef", Name: "M DMG-10%", Found: "Mage Robe, Silver Circlet", Mastered: false},
				{Type: "MagDef", Name: "M DMG-20%", Found: "Hempen Robe, Jasper Robe", Mastered: false},
				{Type: "MagDef", Name: "M DMG-30%", Found: "Green Robe", Mastered: false},
				{Type: "MagDef", Name: "M DMG Soak 10", Found: "Elf Cap", Mastered: false},
				{Type: "MagDef", Name: "M FIRE-50%", Found: "FirePendant, Dragonblood Charm", Mastered: false},
				{Type: "MagDef", Name: "M WATER-50%", Found: "WaterPendant", Mastered: false},
				{Type: "MagDef", Name: "M AIR-50%", Found: "AirPendant", Mastered: false},
				{Type: "MagDef", Name: "M EARTH-50%", Found: "EarthPendant", Mastered: false},
				{Type: "MagDef", Name: "M DARK-50%", Found: "Black Hat", Mastered: false},
				{Type: "MagDef", Name: "Spell Resist: 30%", Found: "Dark Robe", Mastered: false},
				{Type: "Passive", Name: "HP+10%", Found: "Body Crystal", Mastered: false},
				{Type: "Passive", Name: "HP+20%", Found: "Emerald Bangle", Mastered: false},
				{Type: "Passive", Name: "MP+10%", Found: "Mind Crystal, Lapis Lily", Mastered: false},
				{Type: "Passive", Name: "MP+20%", Found: "Sapphire Bangle, SoulStone", Mastered: false},
				{Type: "Passive", Name: "Antibody", Found: "Snakestone, Viper's Eye", Mastered: false},
				{Type: "Passive", Name: "Loquacity", Found: "Sorcerer's Soul", Mastered: false},
				{Type: "Passive", Name: "Suppleness", Found: "Dragonblood Charm, Warlord's Soul", Mastered: false},
				{Type: "Passive", Name: "Insomnia", Found: "Cog Necklace, MoonstoneRing, Moonstone", Mastered: false},
				{Type: "Passive", Name: "Clarity", Found: "Amethyst, Amethyst Earring", Mastered: false},
				{Type: "Passive", Name: "Locomotion", Found: "Belt of Movement", Mastered: false},
				{Type: "Passive", Name: "Bright Eyes", Found: "OnyxRing, SolakianAmulet", Mastered: false},
				{Type: "Passive", Name: "Purity", Found: "Yalortian Robe", Mastered: false},
				{Type: "Passive", Name: "Vim", Found: "Bonestone", Mastered: false},
				{Type: "Passive", Name: "STR+1", Found: "FireOpal, Scarlet Stole +2", Mastered: false},
				{Type: "Passive", Name: "STR+2", Found: "Ruby, Scarlet Stole +4", Mastered: false},
				{Type: "Passive", Name: "STR+3", Found: "Scarlet Stole +6", Mastered: false},
				{Type: "Passive", Name: "VIT+1", Found: "Jade, Green Stole +2", Mastered: false},
				{Type: "Passive", Name: "VIT+2", Found: "Emerald, Green Stole +4", Mastered: false},
				{Type: "Passive", Name: "VIT+3", Found: "Green Stole +6", Mastered: false},
				{Type: "Passive", Name: "SPR+1", Found: "Aquamarine, Azure Stole +2", Mastered: false},
				{Type: "Passive", Name: "SPR+2", Found: "Sapphire, Azure Stole +4", Mastered: false},
				{Type: "Passive", Name: "SPR+3", Found: "Azure Stole +6", Mastered: false},
				{Type: "Passive", Name: "AGL+1", Found: "Bandit Leather, Topaz", Mastered: false},
				{Type: "Passive", Name: "AGL+2", Found: "Boots of Celerity", Mastered: false},
				{Type: "Passive", Name: "Resist EARTH", Found: "GeoJacket", Mastered: false},
				{Type: "Passive", Name: "Resist DARK", Found: "Night Jacket", Mastered: false},
				{Type: "Passive", Name: "Resist AETHER", Found: "Astral Wanderer's Garb, Turquoise", Mastered: false},
				{Type: "Passive", Name: "Rainbow Aura Lv.1", Found: "LesserRainbowShirt, Rainbow Disc", Mastered: false},
				{Type: "Passive", Name: "SOS Regen", Found: "Kind Star", Mastered: false},
				{Type: "Passive", Name: "SOS Berserk", Found: "Horned Helm", Mastered: false},
				{Type: "Passive", Name: "EXP+20%", Found: "Candriathope", Mastered: false},
				{Type: "Passive", Name: "Double AP", Found: "EveningStar", Mastered: false},
				{Type: "Passive", Name: "Double Gold", Found: "Regal Crown", Mastered: false},
				{Type: "Passive", Name: "Loot Finder Lv.1", Found: "Lucky Coin", Mastered: false}
			]
		},
		Sharla: {
			Image:"Sharla",
			Name:"Sharla",
			Skills:[
				{Type: "Aeromancy", Name: "Lightning Bolt", Found: "Wing Spear", Mastered: false},
				{Type: "Aeromancy", Name: "Thunderbolt", Found: "Magic Poker", Mastered: false},
				{Type: "Aeromancy", Name: "Healing Wind", Found: "Topaz", Mastered: false},
				{Type: "Aeromancy", Name: "Null Air Once", Found: "Iron Spear", Mastered: false},
				{Type: "Aeromancy", Name: "Remove Paralysis", Found: "Iron Spear", Mastered: false},
				{Type: "Aeromancy", Name: "Aero Shell", Found: "Obelisk", Mastered: false},
				{Type: "Aeromancy", Name: "Gust Shield", Found: "Desert Spear", Mastered: false},
				{Type: "Aeromancy", Name: "Agility Boost", Found: "Boots of Celerity", Mastered: false},
				{Type: "PhysAtk", Name: "DMG+10%", Found: "Stingstick", Mastered: false},
				{Type: "PhysAtk", Name: "DMG+20%", Found: "Firefang", Mastered: false},
				{Type: "PhysAtk", Name: "Accuracy+50%", Found: "Scoping Lens", Mastered: false},
				{Type: "PhysAtk", Name: "Soulstrike", Found: "Ember Spear, Wing Spear", Mastered: false},
				{Type: "PhysAtk", Name: "Quarry: SPIRIT", Found: "Wispstone", Mastered: false},
				{Type: "PhysAtk", Name: "Degeneration 10%", Found: "Onyx", Mastered: false},
				{Type: "PhysAtk", Name: "Drain HP 10%", Found: "BloodOpal", Mastered: false},
				{Type: "PhysAtk", Name: "P+Poison 20%", Found: "Stingstick", Mastered: false},
				{Type: "PhysDef", Name: "DMG-10%", Found: "Snakemail, GoldRing Gauntlet", Mastered: false},
				{Type: "PhysDef", Name: "DMG-20%", Found: "Steel Stole, Magic Shirt, Inventing Coat", Mastered: false},
				{Type: "PhysDef", Name: "DMG-30%", Found: "Golden Gauntlet", Mastered: false},
				{Type: "PhysDef", Name: "DMG Soak 10", Found: "Pickaxe Pendant", Mastered: false},
				{Type: "PhysDef", Name: "DMG Soak 20", Found: "Spiked Hide Armour, Reinforced Leather", Mastered: false},
				{Type: "PhysDef", Name: "DMG Soak 30", Found: "Steel Stole", Mastered: false},
				{Type: "PhysDef", Name: "Evasion 20%", Found: "Bandit Leather, Eclipse Amulet", Mastered: false},
				{Type: "MagAtk", Name: "M DMG+10%", Found: "Scoping Lens", Mastered: false},
				{Type: "MagAtk", Name: "M DMG+20%", Found: "Magic Poker, Feather Crest", Mastered: false},
				{Type: "MagAtk", Name: "M FIRE+20%", Found: "Ember Spear", Mastered: false},
				{Type: "MagAtk", Name: "M AIR+20%", Found: "Wing Spear", Mastered: false},
				{Type: "MagAtk", Name: "M+Stun 20%", Found: "Feather Charm", Mastered: false},
				{Type: "MagDef", Name: "M DMG-10%", Found: "Mage Robe, Silver Circlet", Mastered: false},
				{Type: "MagDef", Name: "M DMG-20%", Found: "Hempen Robe, Jasper Robe", Mastered: false},
				{Type: "MagDef", Name: "M DMG-30%", Found: "Green Robe", Mastered: false},
				{Type: "MagDef", Name: "M DMG Soak 10", Found: "Elf Cap", Mastered: false},
				{Type: "MagDef", Name: "M FIRE-50%", Found: "FirePendant, Dragonblood Charm", Mastered: false},
				{Type: "MagDef", Name: "M WATER-50%", Found: "WaterPendant", Mastered: false},
				{Type: "MagDef", Name: "M AIR-50%", Found: "AirPendant", Mastered: false},
				{Type: "MagDef", Name: "M EARTH-50%", Found: "EarthPendant", Mastered: false},
				{Type: "MagDef", Name: "M DARK-50%", Found: "Black Hat", Mastered: false},
				{Type: "MagDef", Name: "Spell Resist: 30%", Found: "Dark Robe", Mastered: false},
				{Type: "Passive", Name: "HP+10%", Found: "Body Crystal", Mastered: false},
				{Type: "Passive", Name: "HP+20%", Found: "Emerald Bangle", Mastered: false},
				{Type: "Passive", Name: "MP+10%", Found: "Mind Crystal, Lapis Lily", Mastered: false},
				{Type: "Passive", Name: "MP+20%", Found: "Sapphire Bangle, SoulStone", Mastered: false},
				{Type: "Passive", Name: "Antibody", Found: "Snakestone, Viper's Eye", Mastered: false},
				{Type: "Passive", Name: "Loquacity", Found: "Sorcerer's Soul", Mastered: false},
				{Type: "Passive", Name: "Suppleness", Found: "Dragonblood Charm, Warlord's Soul", Mastered: false},
				{Type: "Passive", Name: "Insomnia", Found: "Cog Necklace, MoonstoneRing, Moonstone", Mastered: false},
				{Type: "Passive", Name: "Clarity", Found: "Amethyst, Amethyst Earring", Mastered: false},
				{Type: "Passive", Name: "Locomotion", Found: "Belt of Movement", Mastered: false},
				{Type: "Passive", Name: "Bright Eyes", Found: "OnyxRing, SolakianAmulet", Mastered: false},
				{Type: "Passive", Name: "Purity", Found: "Yalortian Robe", Mastered: false},
				{Type: "Passive", Name: "Vim", Found: "Bonestone", Mastered: false},
				{Type: "Passive", Name: "STR+1", Found: "FireOpal, Scarlet Stole +2", Mastered: false},
				{Type: "Passive", Name: "STR+2", Found: "Ruby, Scarlet Stole +4", Mastered: false},
				{Type: "Passive", Name: "STR+3", Found: "Scarlet Stole +6", Mastered: false},
				{Type: "Passive", Name: "VIT+1", Found: "Jade, Green Stole +2", Mastered: false},
				{Type: "Passive", Name: "VIT+2", Found: "Emerald, Green Stole +4", Mastered: false},
				{Type: "Passive", Name: "VIT+3", Found: "Green Stole +6", Mastered: false},
				{Type: "Passive", Name: "SPR+1", Found: "Aquamarine, Azure Stole +2", Mastered: false},
				{Type: "Passive", Name: "SPR+2", Found: "Sapphire, Azure Stole +4", Mastered: false},
				{Type: "Passive", Name: "SPR+3", Found: "Azure Stole +6", Mastered: false},
				{Type: "Passive", Name: "AGL+1", Found: "Bandit Leather, Topaz", Mastered: false},
				{Type: "Passive", Name: "AGL+2", Found: "Boots of Celerity", Mastered: false},
				{Type: "Passive", Name: "Resist EARTH", Found: "GeoJacket", Mastered: false},
				{Type: "Passive", Name: "Resist DARK", Found: "Night Jacket", Mastered: false},
				{Type: "Passive", Name: "Resist AETHER", Found: "Astral Wanderer's Garb, Turquoise", Mastered: false},
				{Type: "Passive", Name: "Rainbow Aura Lv.1", Found: "LesserRainbowShirt, Rainbow Disc", Mastered: false},
				{Type: "Passive", Name: "SOS Regen", Found: "Kind Star", Mastered: false},
				{Type: "Passive", Name: "SOS Berserk", Found: "Horned Helm", Mastered: false},
				{Type: "Passive", Name: "EXP+20%", Found: "Candriathope", Mastered: false},
				{Type: "Passive", Name: "Double AP", Found: "EveningStar", Mastered: false},
				{Type: "Passive", Name: "Double Gold", Found: "Regal Crown", Mastered: false},
				{Type: "Passive", Name: "Loot Finder Lv.1", Found: "Lucky Coin", Mastered: false}
			]
		},
		Sslenck: {
			Image:"Sslen'ck",
			Name:"Sslen'ck",
			Skills:[
				{Type: "DragonTech", Name: "Fire Breath", Found: "Starting Skill", Mastered: true},
				{Type: "DragonTech", Name: "Fire Stream", Found: "Drackal Crescent", Mastered: false},
				{Type: "DragonTech", Name: "Perforate", Found: "Bone Axe", Mastered: false},
				{Type: "DragonTech", Name: "Boost", Found: "Mighty Axe", Mastered: false},
				{Type: "DragonTech", Name: "Earth Slash", Found: "Stone Axe", Mastered: false},
				{Type: "PhysAtk", Name: "DMG+10%", Found: "Greataxe", Mastered: false},
				{Type: "PhysAtk", Name: "DMG+20%", Found: "Sun Axe, Iron Axe", Mastered: false},
				{Type: "PhysAtk", Name: "Accuracy+50%", Found: "Scoping Lens", Mastered: false},
				{Type: "PhysAtk", Name: "Soulstrike", Found: "Drackal Crescent", Mastered: false},
				{Type: "PhysAtk", Name: "Quarry: BEAST", Found: "Bone Axe", Mastered: false},
				{Type: "PhysAtk", Name: "Quarry: DRAGON", Found: "Drackal Crescent", Mastered: false},
				{Type: "PhysAtk", Name: "Quarry: UNDEAD", Found: "Silver Axe", Mastered: false},
				{Type: "PhysAtk", Name: "Quarry: HUMAN", Found: "Iron  Axe", Mastered: false},
				{Type: "PhysAtk", Name: "Quarry: INSECT", Found: "Mighty Axe", Mastered: false},
				{Type: "PhysAtk", Name: "Quarry: SPIRIT", Found: "Wispstone", Mastered: false},
				{Type: "PhysAtk", Name: "Degeneration 10%", Found: "Onyx", Mastered: false},
				{Type: "PhysAtk", Name: "Drain HP 10%", Found: "BloodOpal", Mastered: false},
				{Type: "PhysDef", Name: "DMG-10%", Found: "Leather Armour, Green Chainmail, Bronze Circlet", Mastered: false},
				{Type: "PhysDef", Name: "DMG-20%", Found: "Steel Stole, Chainmail, Copper Breastplate", Mastered: false},
				{Type: "PhysDef", Name: "DMG-30%", Found: "Iron Armour, Mythril Armour, Golden Gauntlet", Mastered: false},
				{Type: "PhysDef", Name: "DMG Soak 10", Found: "Pickaxe Pendant", Mastered: false},
				{Type: "PhysDef", Name: "DMG Soak 20", Found: "Spiked Hide Armour, Reinforced Armour, Breastplate", Mastered: false},
				{Type: "PhysDef", Name: "DMG Soak 30", Found: "Steel Stole, Mythril Armour", Mastered: false},
				{Type: "PhysDef", Name: "LIGHT-50%", Found: "Solakian Platemail", Mastered: false},
				{Type: "PhysDef", Name: "Evasion 20%", Found: "Bandit Leather, Eclipse Amulet", Mastered: false},
				{Type: "MagAtk", Name: "M DMG+10%", Found: "Scoping Lens", Mastered: false},
				{Type: "MagAtk", Name: "M DMG+20%", Found: "Feather Crest", Mastered: false},
				{Type: "MagDef", Name: "M DMG-10%", Found: "Green Chainmail, Silver Circlet", Mastered: false},
				{Type: "MagDef", Name: "M DMG Soak 10", Found: "Elf Cap", Mastered: false},
				{Type: "MagDef", Name: "M FIRE-50%", Found: "FirePendant, Dragonblood Charm", Mastered: false},
				{Type: "MagDef", Name: "M WATER-50%", Found: "WaterPendant", Mastered: false},
				{Type: "MagDef", Name: "M AIR-50%", Found: "AirPendant", Mastered: false},
				{Type: "MagDef", Name: "M EARTH-50%", Found: "EarthPendant", Mastered: false},
				{Type: "MagDef", Name: "M DARK-50%", Found: "Black Hat", Mastered: false},
				{Type: "Passive", Name: "Dragon's Blood", Found: "Starting Skill", Mastered: true},
				{Type: "Passive", Name: "HP+10%", Found: "Body Crystal", Mastered: false},
				{Type: "Passive", Name: "HP+20%", Found: "Emerald Bangle", Mastered: false},
				{Type: "Passive", Name: "MP+10%", Found: "Lapis Lily, Mind Crystal", Mastered: false},
				{Type: "Passive", Name: "MP+20%", Found: "Sapphire Bangle, SoulStone", Mastered: false},
				{Type: "Passive", Name: "Antibody", Found: "Snakestone, Snakemail, Viper's Eye", Mastered: false},
				{Type: "Passive", Name: "Loquacity", Found: "Sorcerer's Soul", Mastered: false},
				{Type: "Passive", Name: "Suppleness", Found: "Dragonblood Charm, Warlord's Soul", Mastered: false},
				{Type: "Passive", Name: "Insomnia", Found: "Cog Necklace, MoonstoneRing, Moonstone", Mastered: false},
				{Type: "Passive", Name: "Clarity", Found: "Amethyst, Amethyst Earring", Mastered: false},
				{Type: "Passive", Name: "Locomotion", Found: "Belt of Movement", Mastered: false},
				{Type: "Passive", Name: "Bright Eyes", Found: "OnyxRing, SolakianAmulet", Mastered: false},
				{Type: "Passive", Name: "Purity", Found: "Bonemail, Solakian Platemail, Yalortian Robe", Mastered: false},
				{Type: "Passive", Name: "Vim", Found: "Bonestone", Mastered: false},
				{Type: "Passive", Name: "STR+1", Found: "FireOpal, Scarlet Stole +2", Mastered: false},
				{Type: "Passive", Name: "STR+2", Found: "Ruby, Scarlet Stole +4", Mastered: false},
				{Type: "Passive", Name: "STR+3", Found: "Scarlet Stole +6", Mastered: false},
				{Type: "Passive", Name: "VIT+1", Found: "Jade, Green Stole +2", Mastered: false},
				{Type: "Passive", Name: "VIT+2", Found: "Emerald, Green Stole +4", Mastered: false},
				{Type: "Passive", Name: "VIT+3", Found: "Green Stole +6", Mastered: false},
				{Type: "Passive", Name: "SPR+1", Found: "Aquamarine, Azure Staff +2", Mastered: false},
				{Type: "Passive", Name: "SPR+2", Found: "Sapphire, Azure Stole +4, Turquoise Armour", Mastered: false},
				{Type: "Passive", Name: "SPR+3", Found: "Azure Stole +6", Mastered: false},
				{Type: "Passive", Name: "AGL+1", Found: "Bandit Leather, Topaz", Mastered: false},
				{Type: "Passive", Name: "AGL+2", Found: "Boots of Celerity", Mastered: false},
				{Type: "Passive", Name: "Resist FIRE", Found: "Flamemail", Mastered: false},
				{Type: "Passive", Name: "Resist WATER", Found: "Trilobite Armour", Mastered: false},
				{Type: "Passive", Name: "Resist EARTH", Found: "GeoJacket", Mastered: false},
				{Type: "Passive", Name: "Resist DARK", Found: "Night Jacket", Mastered: false},
				{Type: "Passive", Name: "Resist AETHER", Found: "Astral Wanderer's Garb, Turquoise", Mastered: false},
				{Type: "Passive", Name: "Rainbow Aura Lv.1", Found: "LesserRainbowShirt, Rainbow Disc", Mastered: false},
				{Type: "Passive", Name: "SOS Regen", Found: "Kind Star", Mastered: false},
				{Type: "Passive", Name: "SOS Berserk", Found: "Horned Helm", Mastered: false},
				{Type: "Passive", Name: "EXP+20%", Found: "Candriathope", Mastered: false},
				{Type: "Passive", Name: "Double AP", Found: "EveningStar", Mastered: false},
				{Type: "Passive", Name: "Double Gold", Found: "Regal Crown", Mastered: false},
				{Type: "Passive", Name: "Loot Finder Lv.1", Found: "Lucky Coin", Mastered: false}
			]
		},
		Solaar: {
			Image:"Solaar",
			Name:"Solaar",
			Skills:[
				{Type: "AstralMagic", Name: "Solar Flare", Found: "Starting Skill", Mastered: true},
				{Type: "AstralMagic", Name: "Galaxy Burst", Found: "Guardian Claw", Mastered: false},
				{Type: "AstralMagic", Name: "Pleasant Sunbeam", Found: "Starting Skill", Mastered: true},
				{Type: "AstralMagic", Name: "Resurrect", Found: "Eclipse Amulet", Mastered: false},
				{Type: "AstralMagic", Name: "Spirit Graft", Found: "Turquoise", Mastered: false},
				{Type: "AstralMagic", Name: "Purity", Found: "Viper Claw", Mastered: false},
				{Type: "AstralMagic", Name: "Astral Form", Found: "SoulStone", Mastered: false},
				{Type: "AstralMagic", Name: "Luncatic Howl", Found: "Star Charm", Mastered: false},
				{Type: "PhysAtk", Name: "DMG+20%", Found: "Raptor Claw", Mastered: false},
				{Type: "PhysAtk", Name: "Critical+20%", Found: "Raptor Claw", Mastered: false},
				{Type: "PhysAtk", Name: "Accuracy+50%", Found: "Scoping Lens", Mastered: false},
				{Type: "PhysAtk", Name: "Quarry: UNDEAD", Found: "Silver Claw", Mastered: false},
				{Type: "PhysAtk", Name: "Quarry: SPIRIT", Found: "Wispstone", Mastered: false},
				{Type: "PhysAtk", Name: "Degeneration 10%", Found: "Onyx", Mastered: false},
				{Type: "PhysAtk", Name: "Drain HP 10%", Found: "BloodOpal", Mastered: false},
				{Type: "PhysAtk", Name: "P+Poison 20%", Found: "Viper Claw", Mastered: false},
				{Type: "PhysDef", Name: "DMG-10%", Found: "Bronze Circlet, Gauntlet, SilverRing", Mastered: false},
				{Type: "PhysDef", Name: "DMG-20%", Found: "Steel Stole", Mastered: false},
				{Type: "PhysDef", Name: "DMG-30%", Found: "Golden Gauntlet", Mastered: false},
				{Type: "PhysDef", Name: "DMG Soak 10", Found: "Pickaxe Pendant", Mastered: false},
				{Type: "PhysDef", Name: "DMG Soak 30", Found: "Steel Stole", Mastered: false},
				{Type: "PhysDef", Name: "Evasion 20%", Found: "Eclipse Amulet", Mastered: false},
				{Type: "MagAtk", Name: "M DMG+10%", Found: "Scoping Lens", Mastered: false},
				{Type: "MagAtk", Name: "M DMG+20%", Found: "Silver Claw, Feather Crest", Mastered: false},
				{Type: "MagAtk", Name: "M DMG+30%", Found: "Guardian Claw", Mastered: false},
				{Type: "MagAtk", Name: "M LIGHT+20%", Found: "Guardian Claw", Mastered: false},
				{Type: "MagDef", Name: "M DMG-10%", Found: "Silver Circlet", Mastered: false},
				{Type: "MagDef", Name: "M DMG Soak 10", Found: "Elf Cap", Mastered: false},
				{Type: "MagDef", Name: "M FIRE-50%", Found: "FirePendant, Dragonblood Charm", Mastered: false},
				{Type: "MagDef", Name: "M WATER-50%", Found: "WaterPendant", Mastered: false},
				{Type: "MagDef", Name: "M AIR-50%", Found: "AirPendant", Mastered: false},
				{Type: "MagDef", Name: "M EARTH-50%", Found: "EarthPendant", Mastered: false},
				{Type: "MagDef", Name: "M DARK-50%", Found: "Black Hat", Mastered: false},
				{Type: "Passive", Name: "HP+10%", Found: "Body Crystal", Mastered: false},
				{Type: "Passive", Name: "HP+20%", Found: "Emerald Bangle", Mastered: false},
				{Type: "Passive", Name: "MP+10%", Found: "Mind Crystal, Lapis Lily", Mastered: false},
				{Type: "Passive", Name: "MP+20%", Found: "Sapphire Bangle, SoulStone", Mastered: false},
				{Type: "Passive", Name: "Antibody", Found: "Snakestone, Viper's Eye", Mastered: false},
				{Type: "Passive", Name: "Loquacity", Found: "Sorcerer's Soul", Mastered: false},
				{Type: "Passive", Name: "Suppleness", Found: "Dragonblood Charm, Warlord's Soul", Mastered: false},
				{Type: "Passive", Name: "Insomnia", Found: "Cog Necklace, MoonstoneRing, Moonstone", Mastered: false},
				{Type: "Passive", Name: "Clarity", Found: "Amethyst, Amethyst Earring", Mastered: false},
				{Type: "Passive", Name: "Locomotion", Found: "Belt of Movement", Mastered: false},
				{Type: "Passive", Name: "Bright Eyes", Found: "OnyxRing, SolakianAmulet", Mastered: false},
				{Type: "Passive", Name: "Vim", Found: "Bonestone", Mastered: false},
				{Type: "Passive", Name: "STR+1", Found: "FireOpal, Scarlet Stole +2", Mastered: false},
				{Type: "Passive", Name: "STR+2", Found: "Ruby, Scarlet Stole +4", Mastered: false},
				{Type: "Passive", Name: "STR+3", Found: "Scarlet Stole +6", Mastered: false},
				{Type: "Passive", Name: "VIT+1", Found: "Jade, Green Stole +2", Mastered: false},
				{Type: "Passive", Name: "VIT+2", Found: "Emerald, Green Stole +4", Mastered: false},
				{Type: "Passive", Name: "VIT+3", Found: "Green Stole +6", Mastered: false},
				{Type: "Passive", Name: "SPR+1", Found: "Aquamarine, Azure Stole +2", Mastered: false},
				{Type: "Passive", Name: "SPR+2", Found: "Sapphire, Azure Stole +4", Mastered: false},
				{Type: "Passive", Name: "SPR+3", Found: "Azure Stole +6", Mastered: false},
				{Type: "Passive", Name: "AGL+1", Found: "Topaz", Mastered: false},
				{Type: "Passive", Name: "AGL+2", Found: "Boots of Celerity", Mastered: false},
				{Type: "Passive", Name: "Resist AETHER", Found: "Turquoise", Mastered: false},
				{Type: "Passive", Name: "Rainbow Aura Lv.1", Found: "Rainbow Disc", Mastered: false},
				{Type: "Passive", Name: "SOS Regen", Found: "Kind Star", Mastered: false},
				{Type: "Passive", Name: "EXP+20%", Found: "Candriathope", Mastered: false},
				{Type: "Passive", Name: "Double AP", Found: "EveningStar", Mastered: false},
				{Type: "Passive", Name: "Double Gold", Found: "Regal Crown", Mastered: false},
				{Type: "Passive", Name: "Loot Finder Lv.1", Found: "Lucky Coin", Mastered: false}
			]
		},
		Elwyen: {
			Image:"Elwyen",
			Name:"Elwyen",
			Skills:[
				{Type: "SirenSongs", Name: "Spirit Song", Found: "Sheet Music I", Mastered: false},
				{Type: "SirenSongs", Name: "Vigorous March", Found: "Sheet Music II", Mastered: false},
				{Type: "SirenSongs", Name: "Solid Sonata", Found: "Sheet Music III", Mastered: false},
				{Type: "SirenSongs", Name: "Runic Rhapsody", Found: "Sheet Music IV", Mastered: false},
				{Type: "SirenSongs", Name: "Dolorous Dirge", Found: "Sheet Music V", Mastered: false},
				{Type: "SirenSongs", Name: "Requiem", Found: "Sheet Music VI", Mastered: false},
				{Type: "SirenSongs", Name: "Ballad of Life", Found: "Sheet Music VII", Mastered: false},
				{Type: "SirenSongs", Name: "Ballad of Balance", Found: "Sheet Music VIII", Mastered: false},
				{Type: "PhysAtk", Name: "DMG+10%", Found: "Silver Harp", Mastered: false},
				{Type: "PhysAtk", Name: "DMG+20%", Found: "Fairy Harp", Mastered: false},
				{Type: "PhysAtk", Name: "DMG+30%", Found: "Astral Harp", Mastered: false},
				{Type: "PhysAtk", Name: "Accuracy+50%", Found: "Scoping Lens", Mastered: false},
				{Type: "PhysAtk", Name: "Soulstrike", Found: "Wave Harp", Mastered: false},
				{Type: "PhysAtk", Name: "Quarry: SPIRIT", Found: "Wispstone", Mastered: false},
				{Type: "PhysAtk", Name: "Degeneration 10%", Found: "Onyx", Mastered: false},
				{Type: "PhysAtk", Name: "Drain HP 10%", Found: "BloodOpal", Mastered: false},
				{Type: "PhysDef", Name: "DMG-10%", Found: "Magic Blouse, Leather Armour, Bronze Circlet", Mastered: false},
				{Type: "PhysDef", Name: "DMG-20%", Found: "Steel Stole, Magic Shirt, Inventing Coat", Mastered: false},
				{Type: "PhysDef", Name: "DMG-30%", Found: "Golden Gauntlet", Mastered: false},
				{Type: "PhysDef", Name: "DMG Soak 10", Found: "Pickaxe Pendant", Mastered: false},
				{Type: "PhysDef", Name: "DMG Soak 20", Found: "Spiked Hide Armour, Reinforced Armour", Mastered: false},
				{Type: "PhysDef", Name: "DMG Soak 30", Found: "Steel Stole", Mastered: false},
				{Type: "PhysDef", Name: "WATER-50%", Found: "Wave Harp", Mastered: false},
				{Type: "PhysDef", Name: "EARTH-50%", Found: "Fairy Harp", Mastered: false},
				{Type: "PhysDef", Name: "DARK-50%", Found: "Silver Harp", Mastered: false},
				{Type: "PhysDef", Name: "AETHER-50%", Found: "Astral Harp", Mastered: false},
				{Type: "PhysDef", Name: "Evasion 20%", Found: "Bandit Leather, Eclipse Amulet", Mastered: false},
				{Type: "PhysDef", Name: "Evasion 50%", Found: "Lapis Beads", Mastered: false},
				{Type: "PhysDef", Name: "Survivor", Found: "Minstrel's Tiara", Mastered: false},
				{Type: "MagAtk", Name: "M DMG+10%", Found: "Scoping Lens", Mastered: false},
				{Type: "MagAtk", Name: "M DMG+20%", Found: "Feather Crest", Mastered: false},
				{Type: "MagDef", Name: "M DMG-10%", Found: "Mage Robe, Silver Circlet", Mastered: false},
				{Type: "MagDef", Name: "M DMG-20%", Found: "Hempen Robe, Jasper Robe, Shaman's Vestment", Mastered: false},
				{Type: "MagDef", Name: "M DMG-30%", Found: "Green Robe", Mastered: false},
				{Type: "MagDef", Name: "M DMG Soak 10", Found: "Elf Cap", Mastered: false},
				{Type: "MagDef", Name: "M FIRE-50%", Found: "FirePendant, Dragonblood Charm", Mastered: false},
				{Type: "MagDef", Name: "M WATER-50%", Found: "WaterPendant", Mastered: false},
				{Type: "MagDef", Name: "M AIR-50%", Found: "AirPendant", Mastered: false},
				{Type: "MagDef", Name: "M EARH-50%", Found: "EarthPendant", Mastered: false},
				{Type: "MagDef", Name: "M DARK-50%", Found: "Black Hat", Mastered: false},
				{Type: "MagDef", Name: "Spell Resist: 30%", Found: "Dark Robe", Mastered: false},
				{Type: "Passive", Name: "HP+10%", Found: "Body Crystal", Mastered: false},
				{Type: "Passive", Name: "HP+20%", Found: "Emerald Bangle", Mastered: false},
				{Type: "Passive", Name: "MP+10%", Found: "Mind Crystal, Lapis Lily", Mastered: false},
				{Type: "Passive", Name: "MP+20%", Found: "Sapphire Bangle, SoulStone", Mastered: false},
				{Type: "Passive", Name: "Antibody", Found: "Snakestone, Viper's Eye", Mastered: false},
				{Type: "Passive", Name: "Loquacity", Found: "Sorcerer's Soul", Mastered: false},
				{Type: "Passive", Name: "Suppleness", Found: "Dragonblood Charm, Warlord's Soul", Mastered: false},
				{Type: "Passive", Name: "Insomnia", Found: "Cog Necklace, MoonstoneRing, Moonstone", Mastered: false},
				{Type: "Passive", Name: "Clarity", Found: "Amethyst, Amethyst Earring", Mastered: false},
				{Type: "Passive", Name: "Locomotion", Found: "Belt of Movement", Mastered: false},
				{Type: "Passive", Name: "Bright Eyes", Found: "OnyxRing, SolakianAmulet", Mastered: false},
				{Type: "Passive", Name: "Purity", Found: "Yalortian Robe", Mastered: false},
				{Type: "Passive", Name: "Vim", Found: "Bonestone", Mastered: false},
				{Type: "Passive", Name: "STR+1", Found: "FireOpal, Scarlet Stole +2", Mastered: false},
				{Type: "Passive", Name: "STR+2", Found: "Ruby, Scarlet Stole +4", Mastered: false},
				{Type: "Passive", Name: "STR+3", Found: "Scarlet Stole +6", Mastered: false},
				{Type: "Passive", Name: "VIT+1", Found: "Jade, Green Stole +2", Mastered: false},
				{Type: "Passive", Name: "VIT+2", Found: "Emerald, Green Stole +4", Mastered: false},
				{Type: "Passive", Name: "VIT+3", Found: "Green Stole +6", Mastered: false},
				{Type: "Passive", Name: "SPR+1", Found: "Aquamarine, Azure Stole +2", Mastered: false},
				{Type: "Passive", Name: "SPR+2", Found: "Sapphire, Azure Stole +4", Mastered: false},
				{Type: "Passive", Name: "SPR+3", Found: "Azure Stole +6", Mastered: false},
				{Type: "Passive", Name: "AGL+1", Found: "Bandit Leather, Topaz", Mastered: false},
				{Type: "Passive", Name: "AGL+2", Found: "Boots of Celerity", Mastered: false},
				{Type: "Passive", Name: "Resist EARTH", Found: "Geojacket", Mastered: false},
				{Type: "Passive", Name: "Resist DARK", Found: "Night Jacket", Mastered: false},
				{Type: "Passive", Name: "Resist AETHER", Found: "Turquoise, Astral Wanderer's Garb", Mastered: false},
				{Type: "Passive", Name: "Rainbow Aura Lv.1", Found: "LesserRainbowShirt, Rainbow Disc", Mastered: false},
				{Type: "Passive", Name: "SOS Regen", Found: "Kind Star", Mastered: false},
				{Type: "Passive", Name: "EXP+20%", Found: "Candriathope, Astral Harp", Mastered: false},
				{Type: "Passive", Name: "Double AP", Found: "EveningStar", Mastered: false},
				{Type: "Passive", Name: "Double Gold", Found: "Regal Crown", Mastered: false},
				{Type: "Passive", Name: "Loot Finder Lv.1", Found: "Lucky Coin", Mastered: false}
			]
		},
		Gloria: {
			Image:"Gloria",
			Name:"Gloria",
			Skills:[
				{Type: "NatureMagic", Name: "Wildfire", Found: "FireOpal, Fire Staff", Mastered: false},
				{Type: "NatureMagic", Name: "Whirlpool", Found: "Aquamarine, Trilobite Staff", Mastered: false},
				{Type: "NatureMagic", Name: "Twister", Found: "Topaz, Air Staff", Mastered: false},
				{Type: "NatureMagic", Name: "Razor Leaf", Found: "Jade, Earth Staff", Mastered: false},
				{Type: "NatureMagic", Name: "Earth Heal", Found: "Earth Staff", Mastered: false},
				{Type: "NatureMagic", Name: "Barkskin", Found: "Emerald Bangle", Mastered: false},
				{Type: "NatureMagic", Name: "Cleanse", Found: "Leaf Charm", Mastered: false},
				{Type: "NatureMagic", Name: "Mass Cleanse", Found: "Yggdrasil's Finger", Mastered: false},
				{Type: "NatureMagic", Name: "Null Fire Once", Found: "Fire Staff", Mastered: false},
				{Type: "NatureMagic", Name: "Null Water Once", Found: "Sapphire Bangle, Trilobite Staff", Mastered: false},
				{Type: "NatureMagic", Name: "Null Air Once", Found: "Air Staff", Mastered: false},
				{Type: "NatureMagic", Name: "Null Earth Once", Found: "GreenBeads", Mastered: false},
				{Type: "PhysAtk", Name: "DMG+20%", Found: "Polemace, Fire Staff", Mastered: false},
				{Type: "PhysAtk", Name: "Accuracy+50%", Found: "Scoping Lens", Mastered: false},
				{Type: "PhysAtk", Name: "Soulstrike", Found: "Earth Staff", Mastered: false},
				{Type: "PhysAtk", Name: "Quarry: SPIRIT", Found: "Wispstone", Mastered: false},
				{Type: "PhysAtk", Name: "Degeneration 10%", Found: "Onyx", Mastered: false},
				{Type: "PhysAtk", Name: "Drain HP 10%", Found: "BloodOpal", Mastered: false},
				{Type: "PhysDef", Name: "DMG-10%", Found: "Magic Blouse, Leather Armour, Bronze Circlet", Mastered: false},
				{Type: "PhysDef", Name: "DMG-20%", Found: "Steel Stole, Magic Shirt, Inventing Coat", Mastered: false},
				{Type: "PhysDef", Name: "DMG-30%", Found: "Golden Gauntlet", Mastered: false},
				{Type: "PhysDef", Name: "DMG Soak 10", Found: "Pickaxe Pendant", Mastered: false},
				{Type: "PhysDef", Name: "DMG Soak 20", Found: "Spiked Hide Armour, Reinforced Armour", Mastered: false},
				{Type: "PhysDef", Name: "DMG Soak 30", Found: "Steel Stole", Mastered: false},
				{Type: "PhysDef", Name: "Evasion 20%", Found: "Bandit Leather, Eclipse Amulet", Mastered: false},
				{Type: "MagAtk", Name: "M DMG+10%", Found: "Scoping Lens", Mastered: false},
				{Type: "MagAtk", Name: "M DMG+20%", Found: "Air Staff, Feather Crest", Mastered: false},
				{Type: "MagAtk", Name: "M DMG+30%", Found: "Yggdrasil's Finger", Mastered: false},
				{Type: "MagAtk", Name: "M Drain HP 10%", Found: "Mahogany Staff", Mastered: false},
				{Type: "MagDef", Name: "M DMG-10%", Found: "Mage Robe, Silver Circlet", Mastered: false},
				{Type: "MagDef", Name: "M DMG-20%", Found: "Hempen Robe, Jasper Robe, Shaman's Vestment", Mastered: false},
				{Type: "MagDef", Name: "M DMG-30%", Found: "Green Robe", Mastered: false},
				{Type: "MagDef", Name: "M DMG Soak 10", Found: "Elf Cap", Mastered: false},
				{Type: "MagDef", Name: "M FIRE-50%", Found: "FirePendant, Dragonblood Charm", Mastered: false},
				{Type: "MagDef", Name: "M WATER-50%", Found: "WaterPendant", Mastered: false},
				{Type: "MagDef", Name: "M AIR-50%", Found: "AirPendant", Mastered: false},
				{Type: "MagDef", Name: "M EARH-50%", Found: "EarthPendant", Mastered: false},
				{Type: "MagDef", Name: "M DARK-50%", Found: "Black Hat", Mastered: false},
				{Type: "MagDef", Name: "Spell Resist: 30%", Found: "Dark Robe", Mastered: false},
				{Type: "Passive", Name: "Nature's Favour", Found: "Shaman's Vestment", Mastered: false},
				{Type: "Passive", Name: "HP+10%", Found: "Body Crystal", Mastered: false},
				{Type: "Passive", Name: "HP+20%", Found: "Emerald Bangle", Mastered: false},
				{Type: "Passive", Name: "MP+10%", Found: "Mind Crystal, Lapis Lily", Mastered: false},
				{Type: "Passive", Name: "MP+20%", Found: "Sapphire Bangle, SoulStone", Mastered: false},
				{Type: "Passive", Name: "Antibody", Found: "Snakestone, Viper's Eye", Mastered: false},
				{Type: "Passive", Name: "Loquacity", Found: "Sorcerer's Soul", Mastered: false},
				{Type: "Passive", Name: "Suppleness", Found: "Dragonblood Charm, Warlord's Soul", Mastered: false},
				{Type: "Passive", Name: "Insomnia", Found: "Cog Necklace, MoonstoneRing, Moonstone", Mastered: false},
				{Type: "Passive", Name: "Clarity", Found: "Amethyst, Amethyst Earring", Mastered: false},
				{Type: "Passive", Name: "Locomotion", Found: "Belt of Movement", Mastered: false},
				{Type: "Passive", Name: "Bright Eyes", Found: "OnyxRing, SolakianAmulet", Mastered: false},
				{Type: "Passive", Name: "Purity", Found: "Yalortian Robe", Mastered: false},
				{Type: "Passive", Name: "Vim", Found: "Bonestone", Mastered: false},
				{Type: "Passive", Name: "STR+1", Found: "FireOpal, Scarlet Stole +2", Mastered: false},
				{Type: "Passive", Name: "STR+2", Found: "Ruby, Scarlet Stole +4", Mastered: false},
				{Type: "Passive", Name: "STR+3", Found: "Scarlet Stole +6", Mastered: false},
				{Type: "Passive", Name: "VIT+1", Found: "Jade, Green Stole +2", Mastered: false},
				{Type: "Passive", Name: "VIT+2", Found: "Emerald, Green Stole +4", Mastered: false},
				{Type: "Passive", Name: "VIT+3", Found: "Green Stole +6", Mastered: false},
				{Type: "Passive", Name: "SPR+1", Found: "Aquamarine, Azure Stole +2", Mastered: false},
				{Type: "Passive", Name: "SPR+2", Found: "Sapphire, Azure Stole +4", Mastered: false},
				{Type: "Passive", Name: "SPR+3", Found: "Azure Stole +6", Mastered: false},
				{Type: "Passive", Name: "AGL+1", Found: "Bandit Leather, Topaz", Mastered: false},
				{Type: "Passive", Name: "AGL+2", Found: "Boots of Celerity", Mastered: false},
				{Type: "Passive", Name: "Resist EARTH", Found: "Geojacket", Mastered: false},
				{Type: "Passive", Name: "Resist DARK", Found: "Night Jacket", Mastered: false},
				{Type: "Passive", Name: "Resist AETHER", Found: "Turquoise, Astral Wanderer's Garb", Mastered: false},
				{Type: "Passive", Name: "Rainbow Aura Lv.1", Found: "LesserRainbowShirt, Rainbow Disc", Mastered: false},
				{Type: "Passive", Name: "SOS Regen", Found: "Kind Star", Mastered: false},
				{Type: "Passive", Name: "EXP+20%", Found: "Candriathope", Mastered: false},
				{Type: "Passive", Name: "Double AP", Found: "EveningStar", Mastered: false},
				{Type: "Passive", Name: "Double Gold", Found: "Regal Crown", Mastered: false},
				{Type: "Passive", Name: "Loot Finder Lv.1", Found: "Lucky Coin", Mastered: false}
			]
		},
		Meraeador: {
			Image:"Meraeador",
			Name:"Meraeador",
			Skills:[
				{Type: "Inventions", Name: "Thermal Spanner", Found: "Cannot be mastered", Mastered: false},
				{Type: "Inventions", Name: "Silver Mirror", Found: "Cannot be mastered", Mastered: false},
				{Type: "Inventions", Name: "Golden Mirror", Found: "Cannot be mastered", Mastered: false},
				{Type: "Inventions", Name: "Flamethrower", Found: "Cannot be mastered", Mastered: false},
				{Type: "Inventions", Name: "Gas-O-Matic", Found: "Cannot be mastered", Mastered: false},
				{Type: "Inventions", Name: "Sleep-O-Matic", Found: "Cannot be mastered", Mastered: false},
				{Type: "Inventions", Name: "Potion Spray", Found: "Cannot be mastered", Mastered: false},
				{Type: "Inventions", Name: "Drill-O-Matic", Found: "Cannot be mastered", Mastered: false},
				{Type: "PhysAtk", Name: "Accuracy+50%", Found: "Scoping Lens", Mastered: false},
				{Type: "PhysAtk", Name: "Quarry: SPIRIT", Found: "Wispstone", Mastered: false},
				{Type: "PhysAtk", Name: "Degeneration 10%", Found: "Onyx", Mastered: false},
				{Type: "PhysAtk", Name: "Drain HP 10%", Found: "BloodOpal", Mastered: false},
				{Type: "PhysDef", Name: "DMG-10%", Found: "Leather Armour, Bronze Circlet, Gauntlet", Mastered: false},
				{Type: "PhysDef", Name: "DMG-20%", Found: "Inventing Coat, Steel Stole, Magic Shirt", Mastered: false},
				{Type: "PhysDef", Name: "DMG-30%", Found: "Golden Gauntlet", Mastered: false},
				{Type: "PhysDef", Name: "DMG Soak 10", Found: "Pickaxe Pendant", Mastered: false},
				{Type: "PhysDef", Name: "DMG Soak 20", Found: "Spiked Hide Armour, Reinforced Armour", Mastered: false},
				{Type: "PhysDef", Name: "DMG Soak 30", Found: "Steel Stole", Mastered: false},
				{Type: "PhysDef", Name: "Evasion 20%", Found: "Bandit Leather, Eclipse Amulet", Mastered: false},
				{Type: "MagAtk", Name: "M DMG+10%", Found: "Scoping Lens", Mastered: false},
				{Type: "MagAtk", Name: "M DMG+20%", Found: "Feather Crest", Mastered: false},
				{Type: "MagDef", Name: "M DMG-10%", Found: "Mage Robe, Silver Circlet", Mastered: false},
				{Type: "MagDef", Name: "M DMG-20%", Found: "Hempen Robe, Japser Robe, Shaman's Vestment", Mastered: false},
				{Type: "MagDef", Name: "M DMG-30%", Found: "Green Robe", Mastered: false},
				{Type: "MagDef", Name: "M DMG Soak 10", Found: "Elf Cap", Mastered: false},
				{Type: "MagDef", Name: "M FIRE-50%", Found: "FirePendant, Dragonblood Charm", Mastered: false},
				{Type: "MagDef", Name: "M WATER-50%", Found: "WaterPendant", Mastered: false},
				{Type: "MagDef", Name: "M AIR-50%", Found: "AirPendant", Mastered: false},
				{Type: "MagDef", Name: "M EARTH-50%", Found: "EarthPendant", Mastered: false},
				{Type: "MagDef", Name: "M DARK-50%", Found: "Black Hat", Mastered: false},
				{Type: "MagDef", Name: "Spell Resist: 30%", Found: "Dark Robe", Mastered: false},
				{Type: "Passive", Name: "HP+10%", Found: "Body Crystal", Mastered: false},
				{Type: "Passive", Name: "HP+20%", Found: "Emerald Bangle", Mastered: false},
				{Type: "Passive", Name: "MP+10%", Found: "Mind Crystal, Lapis Lily", Mastered: false},
				{Type: "Passive", Name: "MP+20%", Found: "Sapphire Bangle, SoulStone", Mastered: false},
				{Type: "Passive", Name: "Antibody", Found: "Snakestone, Viper's Eye", Mastered: false},
				{Type: "Passive", Name: "Loquacity", Found: "Sorcerer's Soul", Mastered: false},
				{Type: "Passive", Name: "Suppleness", Found: "Dragonblood Charm, Warlord's Soul", Mastered: false},
				{Type: "Passive", Name: "Insomnia", Found: "Cog Necklace, MoonstoneRing, Moonstone", Mastered: false},
				{Type: "Passive", Name: "Clarity", Found: "Amethyst, Amethyst Earring", Mastered: false},
				{Type: "Passive", Name: "Locomotion", Found: "Belt of Movement", Mastered: false},
				{Type: "Passive", Name: "Bright Eyes", Found: "OnyxRing, SolakianAmulet", Mastered: false},
				{Type: "Passive", Name: "Purity", Found: "Yalortian Robe", Mastered: false},
				{Type: "Passive", Name: "Vim", Found: "Bonestone", Mastered: false},
				{Type: "Passive", Name: "STR+1", Found: "FireOpal, Scarlet Stole +2", Mastered: false},
				{Type: "Passive", Name: "STR+2", Found: "Ruby, Scarlet Stole +4", Mastered: false},
				{Type: "Passive", Name: "STR+3", Found: "Scarlet Stole +6", Mastered: false},
				{Type: "Passive", Name: "VIT+1", Found: "Jade, Green Stole +2", Mastered: false},
				{Type: "Passive", Name: "VIT+2", Found: "Emerald, Green Stole +4", Mastered: false},
				{Type: "Passive", Name: "VIT+3", Found: "Green Stole +6", Mastered: false},
				{Type: "Passive", Name: "SPR+1", Found: "Aquamarine, Azure Stole +2", Mastered: false},
				{Type: "Passive", Name: "SPR+2", Found: "Sapphire, Azure Stole +4", Mastered: false},
				{Type: "Passive", Name: "SPR+3", Found: "Azure Stole +6", Mastered: false},
				{Type: "Passive", Name: "AGL+1", Found: "Bandit Leather, Topaz", Mastered: false},
				{Type: "Passive", Name: "AGL+2", Found: "Boots of Celerity", Mastered: false},
				{Type: "Passive", Name: "Resist EARTH", Found: "Geojacket", Mastered: false},
				{Type: "Passive", Name: "Resist DARK", Found: "Night Jacket", Mastered: false},
				{Type: "Passive", Name: "Resist AETHER", Found: "Turquoise, Astral Wanderer's Garb", Mastered: false},
				{Type: "Passive", Name: "Rainbow Aura Lv.1", Found: "LesserRainbowShirt, Rainbow Disc", Mastered: false},
				{Type: "Passive", Name: "SOS Regen", Found: "Kind Star", Mastered: false},
				{Type: "Passive", Name: "EXP+20%", Found: "Candriathope", Mastered: false},
				{Type: "Passive", Name: "Double AP", Found: "EveningStar", Mastered: false},
				{Type: "Passive", Name: "Double Gold", Found: "Regal Crown", Mastered: false},
				{Type: "Passive", Name: "Loot Finder Lv.1", Found: "Lucky Coin", Mastered: false}
			]
		},
		Vehrn: {
			Image:"Vehrn",
			Name:"Vehrn",
			Skills:[
				{Type: "HolyArts", Name: "Smite Evil", Found: "Bronze Sword", Mastered: false},
				{Type: "HolyArts", Name: "Disrupt Undead", Found: "Silver Sword", Mastered: false},
				{Type: "HolyArts", Name: "Divine Glory", Found: "Righteous Justice", Mastered: false},
				{Type: "HolyArts", Name: "Lay on Hands", Found: "Righteous Honour", Mastered: false},
				{Type: "HolyArts", Name: "Green Lightning", Found: "YalortianAmulet", Mastered: false},
				{Type: "HolyArts", Name: "Emerald Shock", Found: "YALORT Charm", Mastered: false},
				{Type: "PhysAtk", Name: "Smite+", Found: "Bronze Sword, Clerical Mace", Mastered: false},
				{Type: "PhysAtk", Name: "Smite X", Found: "Righteous Justice", Mastered: false},
				{Type: "PhysAtk", Name: "DMG+10%", Found: "Iron Sword, Mace, Mythril Sword", Mastered: false},
				{Type: "PhysAtk", Name: "DMG+20%", Found: "Longsword, Sun Sword", Mastered: false},
				{Type: "PhysAtk", Name: "DMG+30%", Found: "Champion Sword, Champion Sword II", Mastered: false},
				{Type: "PhysAtk", Name: "Critical+20%", Found: "Xantusian Scimitar", Mastered: false},
				{Type: "PhysAtk", Name: "Accuracy+50%", Found: "Scoping Lens", Mastered: false},
				{Type: "PhysAtk", Name: "Soulstrike", Found: "Champion Sword II, Righteous Justice", Mastered: false},
				{Type: "PhysAtk", Name: "Quarry: UNDEAD", Found: "Silver Sword", Mastered: false},
				{Type: "PhysAtk", Name: "Quarry: SPIRIT", Found: "Wispstone", Mastered: false},
				{Type: "PhysAtk", Name: "Degeneration 10%", Found: "ShadowBlade, Onyx", Mastered: false},
				{Type: "PhysAtk", Name: "Drain HP 10%", Found: "Blood Sword, BloodOpal", Mastered: false},
				{Type: "PhysAtk", Name: "P+Bleed 20%", Found: "Cursed Blade", Mastered: false},
				{Type: "PhysDef", Name: "DMG-10%", Found: "Wooden Shield, Green Chainmail, SilverRing", Mastered: false},
				{Type: "PhysDef", Name: "DMG-20%", Found: "Chainmail, Copper Breastplate, Righteous Honour", Mastered: false},
				{Type: "PhysDef", Name: "DMG-30%", Found: "Iron Armour, Mythril Platemail, Golden Gauntlet", Mastered: false},
				{Type: "PhysDef", Name: "DMG Soak 10", Found: "Bronze Shield, Pickaxe Pendant", Mastered: false},
				{Type: "PhysDef", Name: "DMG Soak 20", Found: "Breastplate, Gold Shield, Spiked Hide Armour", Mastered: false},
				{Type: "PhysDef", Name: "DMG Soak 30", Found: "Steel Stole, Mythril Platemail", Mastered: false},
				{Type: "PhysDef", Name: "AIR-50%", Found: "Wing Shield", Mastered: false},
				{Type: "PhysDef", Name: "LIGHT-50%", Found: "Shield of Light, Solakian Platemail", Mastered: false},
				{Type: "PhysDef", Name: "DARK-50%", Found: "Shield of Darkness", Mastered: false},
				{Type: "PhysDef", Name: "Evasion 20%", Found: "Bandit Leather, Eclipse Amulet", Mastered: false},
				{Type: "MagAtk", Name: "M DMG+10%", Found: "Scoping Lens", Mastered: false},
				{Type: "MagAtk", Name: "M DMG+20%", Found: "Feather Crest", Mastered: false},
				{Type: "MagDef", Name: "M DMG-10%", Found: "Green Chainmail, Silver Circlet", Mastered: false},
				{Type: "MagDef", Name: "M DMG-20%", Found: "Rune Shield, Righteous Honour", Mastered: false},
				{Type: "MagDef", Name: "M DMG Soak 10", Found: "Elf Cap", Mastered: false},
				{Type: "MagDef", Name: "M DMG Soak 20", Found: "Rune Shield +", Mastered: false},
				{Type: "MagDef", Name: "M FIRE-50%", Found: "FirePendant, Dragonblood Charm", Mastered: false},
				{Type: "MagDef", Name: "M WATER-50%", Found: "WaterPendant", Mastered: false},
				{Type: "MagDef", Name: "M AIR-50%", Found: "Wing Shield, AirPendant", Mastered: false},
				{Type: "MagDef", Name: "M EARTH-50%", Found: "EarthPendant", Mastered: false},
				{Type: "MagDef", Name: "M LIGHT-50%", Found: "Shield of Light", Mastered: false},
				{Type: "MagDef", Name: "M DARK-50%", Found: "Shield of Darkness, Black Hat", Mastered: false},
				{Type: "MagDef", Name: "Spell Resist: 30%", Found: "Glyph Shield", Mastered: false},
				{Type: "Passive", Name: "HP+10%", Found: "Body Crystal", Mastered: false},
				{Type: "Passive", Name: "HP+20%", Found: "Emerald Bangle", Mastered: false},
				{Type: "Passive", Name: "MP+10%", Found: "Lapis Lily, Mind Crystal", Mastered: false},
				{Type: "Passive", Name: "MP+20%", Found: "Sapphire Bangle, SoulStone", Mastered: false},
				{Type: "Passive", Name: "Antibody", Found: "Snakestone, Snakemail, Viper's Eye", Mastered: false},
				{Type: "Passive", Name: "Loquacity", Found: "Sorcerer's Soul", Mastered: false},
				{Type: "Passive", Name: "Suppleness", Found: "Dragonblood Charm, Warlord's Soul", Mastered: false},
				{Type: "Passive", Name: "Insomnia", Found: "Cog Necklace, MoonstoneRing, Moonstone", Mastered: false},
				{Type: "Passive", Name: "Clarity", Found: "Amethyst, Amethyst Earring", Mastered: false},
				{Type: "Passive", Name: "Locomotion", Found: "Belt of Movement", Mastered: false},
				{Type: "Passive", Name: "Bright Eyes", Found: "OnyxRing, SolakianAmulet", Mastered: false},
				{Type: "Passive", Name: "Purity", Found: "Bonemail, Solakian Platemail, Yalortian Robe", Mastered: false},
				{Type: "Passive", Name: "Vim", Found: "Bonestone", Mastered: false},
				{Type: "Passive", Name: "STR+1", Found: "FireOpal, Scarlet Stole +2", Mastered: false},
				{Type: "Passive", Name: "STR+2", Found: "Ruby, Scarlet Stole +4", Mastered: false},
				{Type: "Passive", Name: "STR+3", Found: "Scarlet Stole +6", Mastered: false},
				{Type: "Passive", Name: "VIT+1", Found: "Jade, Green Stole +2", Mastered: false},
				{Type: "Passive", Name: "VIT+2", Found: "Emerald, Green Stole +4", Mastered: false},
				{Type: "Passive", Name: "VIT+3", Found: "Green Stole +6", Mastered: false},
				{Type: "Passive", Name: "SPR+1", Found: "Aquamarine, Azure Staff +2", Mastered: false},
				{Type: "Passive", Name: "SPR+2", Found: "Sapphire, Azure Stole +4, Turquoise Armour", Mastered: false},
				{Type: "Passive", Name: "SPR+3", Found: "Azure Stole +6", Mastered: false},
				{Type: "Passive", Name: "AGL+1", Found: "Bandit Leather, Topaz", Mastered: false},
				{Type: "Passive", Name: "AGL+2", Found: "Boots of Celerity", Mastered: false},
				{Type: "Passive", Name: "Resist FIRE", Found: "Flamemail", Mastered: false},
				{Type: "Passive", Name: "Resist WATER", Found: "Trilobite Armour", Mastered: false},
				{Type: "Passive", Name: "Resist EARTH", Found: "GeoJacket", Mastered: false},
				{Type: "Passive", Name: "Resist DARK", Found: "Night Jacket", Mastered: false},
				{Type: "Passive", Name: "Resist AETHER", Found: "Astral Wanderer's Garb, Turquoise", Mastered: false},
				{Type: "Passive", Name: "Rainbow Aura Lv.1", Found: "LesserRainbowShirt, Rainbow Disc", Mastered: false},
				{Type: "Passive", Name: "SOS Regen", Found: "Kind Star", Mastered: false},
				{Type: "Passive", Name: "SOS Berserk", Found: "Horned Helm", Mastered: false},
				{Type: "Passive", Name: "EXP+20%", Found: "Candriathope", Mastered: false},
				{Type: "Passive", Name: "Double AP", Found: "EveningStar", Mastered: false},
				{Type: "Passive", Name: "Double Gold", Found: "Regal Crown", Mastered: false},
				{Type: "Passive", Name: "Loot Finder Lv.1", Found: "Lucky Coin", Mastered: false}
			]
		},
		Zach: {
			Image:"Zach",
			Name:"Zach",
			Skills:[
				{Type: "Techniques", Name: "Berserk", Found: "Shashiik", Mastered: false},
				{Type: "Techniques", Name: "Crescendo Slash", Found: "Boneslicer", Mastered: false},
				{Type: "Techniques", Name: "Sure Slash", Found: "Twin Trilobites", Mastered: false},
				{Type: "Techniques", Name: "Coup de Grace", Found: "Two Moons", Mastered: false},
				{Type: "Techniques", Name: "Sinstrike", Found: "Snakemail", Mastered: false},
				{Type: "Techniques", Name: "Immoral Injustice", Found: "Yin and Yang", Mastered: false},
				{Type: "PhysAtk", Name: "DMG+20%", Found: "Shashiik", Mastered: false},
				{Type: "PhysAtk", Name: "Critical+20%", Found: "Two Moons", Mastered: false},
				{Type: "PhysAtk", Name: "Accuracy+50%", Found: "Scoping Lens", Mastered: false},
				{Type: "PhysAtk", Name: "Soulstrike", Found: "Shashiik, Eagle Wings", Mastered: false},
				{Type: "PhysAtk", Name: "Quarry: UNDEAD", Found: "Boneslicer", Mastered: false},
				{Type: "PhysAtk", Name: "Quarry: INSECT", Found: "Twin Trilobites", Mastered: false},
				{Type: "PhysAtk", Name: "Quarry: SPIRIT", Found: "Wispstone", Mastered: false},
				{Type: "PhysAtk", Name: "Degeneration 10%", Found: "Onyx", Mastered: false},
				{Type: "PhysAtk", Name: "Drain HP 10%", Found: "BloodOpal", Mastered: false},
				{Type: "PhysDef", Name: "DMG-10%", Found: "Green Chainmail, Snakemail, Gauntlet", Mastered: false},
				{Type: "PhysDef", Name: "DMG-20%", Found: "Chainmail, Copper Breastplate, Steel Stole", Mastered: false},
				{Type: "PhysDef", Name: "DMG-30%", Found: "Golden Gauntlet", Mastered: false},
				{Type: "PhysDef", Name: "DMG Soak 10", Found: "Pickaxe Pendant", Mastered: false},
				{Type: "PhysDef", Name: "DMG Soak 20", Found: "Spiked Hide Armour, Skull Helm, Breastplate", Mastered: false},
				{Type: "PhysDef", Name: "DMG Soak 30", Found: "Steel Stole", Mastered: false},
				{Type: "PhysDef", Name: "Evasion 20%", Found: "Bandit Leather, Eclipse Amulet", Mastered: false},
				{Type: "PhysDef", Name: "Evasion 50%", Found: "Yin and Yang", Mastered: false},
				{Type: "MagAtk", Name: "M DMG+10%", Found: "Scoping Lens", Mastered: false},
				{Type: "MagAtk", Name: "M DMG+20%", Found: "Feather Crest", Mastered: false},
				{Type: "MagDef", Name: "M DMG-10%", Found: "Green Chainmail, Silver Circlet", Mastered: false},
				{Type: "MagDef", Name: "M DMG Soak 10", Found: "Elf Cap", Mastered: false},
				{Type: "MagDef", Name: "M FIRE-50%", Found: "FirePendant, Dragonblood Charm", Mastered: false},
				{Type: "MagDef", Name: "M WATER-50%", Found: "WaterPendant", Mastered: false},
				{Type: "MagDef", Name: "M AIR-50%", Found: "AirPendant", Mastered: false},
				{Type: "MagDef", Name: "M EARTH-50%", Found: "EarthPendant", Mastered: false},
				{Type: "MagDef", Name: "M DARK-50%", Found: "Black Hat", Mastered: false},
				{Type: "Passive", Name: "HP+10%", Found: "Body Crystal", Mastered: false},
				{Type: "Passive", Name: "HP+20%", Found: "Emerald Bangle", Mastered: false},
				{Type: "Passive", Name: "MP+10%", Found: "Lapis Lily, Mind Crystal", Mastered: false},
				{Type: "Passive", Name: "MP+20%", Found: "Sapphire Bangle, SoulStone", Mastered: false},
				{Type: "Passive", Name: "Antibody", Found: "Snakestone, Snakemail, Viper's Eye", Mastered: false},
				{Type: "Passive", Name: "Loquacity", Found: "Sorcerer's Soul", Mastered: false},
				{Type: "Passive", Name: "Suppleness", Found: "Dragonblood Charm, Warlord's Soul", Mastered: false},
				{Type: "Passive", Name: "Insomnia", Found: "Cog Necklace, MoonstoneRing, Moonstone", Mastered: false},
				{Type: "Passive", Name: "Clarity", Found: "Amethyst, Amethyst Earring", Mastered: false},
				{Type: "Passive", Name: "Locomotion", Found: "Belt of Movement", Mastered: false},
				{Type: "Passive", Name: "Bright Eyes", Found: "OnyxRing, SolakianAmulet", Mastered: false},
				{Type: "Passive", Name: "Purity", Found: "Bonemail, Solakian Platemail, Yalortian Robe", Mastered: false},
				{Type: "Passive", Name: "Vim", Found: "Bonestone", Mastered: false},
				{Type: "Passive", Name: "STR+1", Found: "FireOpal, Scarlet Stole +2", Mastered: false},
				{Type: "Passive", Name: "STR+2", Found: "Ruby, Scarlet Stole +4", Mastered: false},
				{Type: "Passive", Name: "STR+3", Found: "Scarlet Stole +6", Mastered: false},
				{Type: "Passive", Name: "VIT+1", Found: "Jade, Green Stole +2", Mastered: false},
				{Type: "Passive", Name: "VIT+2", Found: "Emerald, Green Stole +4", Mastered: false},
				{Type: "Passive", Name: "VIT+3", Found: "Green Stole +6", Mastered: false},
				{Type: "Passive", Name: "SPR+1", Found: "Aquamarine, Azure Staff +2", Mastered: false},
				{Type: "Passive", Name: "SPR+2", Found: "Sapphire, Azure Stole +4, Turquoise Armour", Mastered: false},
				{Type: "Passive", Name: "SPR+3", Found: "Azure Stole +6", Mastered: false},
				{Type: "Passive", Name: "AGL+1", Found: "Bandit Leather, Topaz", Mastered: false},
				{Type: "Passive", Name: "AGL+2", Found: "Boots of Celerity, Eagle Wings", Mastered: false},
				{Type: "Passive", Name: "Resist FIRE", Found: "Flamemail", Mastered: false},
				{Type: "Passive", Name: "Resist WATER", Found: "Trilobite Armour", Mastered: false},
				{Type: "Passive", Name: "Resist EARTH", Found: "GeoJacket", Mastered: false},
				{Type: "Passive", Name: "Resist DARK", Found: "Night Jacket", Mastered: false},
				{Type: "Passive", Name: "Resist AETHER", Found: "Astral Wanderer's Garb, Turquoise", Mastered: false},
				{Type: "Passive", Name: "Rainbow Aura Lv.1", Found: "LesserRainbowShirt, Rainbow Disc", Mastered: false},
				{Type: "Passive", Name: "SOS Regen", Found: "Kind Star", Mastered: false},
				{Type: "Passive", Name: "SOS Berserk", Found: "Horned Helm", Mastered: false},
				{Type: "Passive", Name: "EXP+20%", Found: "Candriathope", Mastered: false},
				{Type: "Passive", Name: "Double AP", Found: "EveningStar", Mastered: false},
				{Type: "Passive", Name: "Double Gold", Found: "Regal Crown", Mastered: false},
				{Type: "Passive", Name: "Loot Finder Lv.1", Found: "Lucky Coin", Mastered: false}
			]
		},
		Legion: {
			Image:"Legion",
			Name:"Legion",
			Skills:[
				{Type: "Mimicry", Name: "Dark Claw", Found: "Drowned Corpse, Punk Monster, Forgotten Face", Mastered: false},
				{Type: "Mimicry", Name: "Blood Claw", Found: "Red Dragon, Bone Demon, Annihilator:Karnos", Mastered: false},
				{Type: "Mimicry", Name: "Money Attack!", Found: "Posh Gruul, Posh Zombie", Mastered: false},
				{Type: "Mimicry", Name: "Blood Drain", Found: "Leech Bat, Albino Bat, Ghoul", Mastered: false},
				{Type: "Mimicry", Name: "Gemsplosion", Found: "Moonstone, Fire Opal, Topaz", Mastered: false},
				{Type: "Mimicry", Name: "Fire Breath", Found: "Lupaazr, Blood Lizard, Magmazard", Mastered: false},
				{Type: "Mimicry", Name: "Bubble Breath", Found: "Angry Cod, Roaming Axolotl, Axolotl", Mastered: false},
				{Type: "Mimicry", Name: "Curse", Found: "Green Soul, Pixie, Whim", Mastered: false},
				{Type: "Mimicry", Name: "Addle Gas", Found: "Pixie, I-Orb Spawn, Chaosoul", Mastered: false},
				{Type: "Mimicry", Name: "Revenge Strike", Found: "Centaur (Male)", Mastered: false},
				{Type: "Mimicry", Name: "1000 Needles", Found: "Happy Johnny", Mastered: false},
				{Type: "Mimicry", Name: "Rage Chord", Found: "Temperance (Fire), Pixie, Charred Bones", Mastered: false},
				{Type: "Mimicry", Name: "Poison Sting", Found: "Wasp, Blade Bee, Poison Bee", Mastered: false},
				{Type: "Mimicry", Name: "Spectral Touch", Found: "Forgotten Face, Apparition", Mastered: false},
				{Type: "Mimicry", Name: "Ripping Slash", Found: "Brown Mantid, Green Mantid, Antlion", Mastered: false},
				{Type: "Mimicry", Name: "Acid", Found: "Balloon, Ooze", Mastered: false},
				{Type: "Mimicry", Name: "Morbid Fondle", Found: "Drowned Corpse, Ghoul, Ghast", Mastered: false},
				{Type: "Mimicry", Name: "Viscous Ooze", Found: "Ooze, Waterdrop, Lava Blob", Mastered: false},
				{Type: "Mimicry", Name: "Spirit Nova", Found: "Green Soul, Blue Soul, Chaosoul", Mastered: false},
				{Type: "Mimicry", Name: "Sombre Tears", Found: "I-Orb, Blue Soul, Black Eye", Mastered: false},
				{Type: "Mimicry", Name: "Needleflare", Found: "Happy Johnny", Mastered: false},
				{Type: "Mimicry", Name: "Fairy Dust", Found: "Rogue Fairy", Mastered: false},
				{Type: "Mimicry", Name: "Heavy Blow", Found: "Golem, Mythril Golem", Mastered: false},
				{Type: "Mimicry", Name: "Raging Inferno", Found: "Fire Guardian, Bone Demon, Annihilator:Karnos", Mastered: false},
				{Type: "Mimicry", Name: "Tsunami", Found: "Water Guardian, Annihilator:Karnos, King of Goznor", Mastered: false},
				{Type: "Mimicry", Name: "Earthquake", Found: "Earth Guardian, Annihilator:Karnos, Bone Demon", Mastered: false},
				{Type: "Mimicry", Name: "Thunderstorm", Found: "Temperance (Air), Bernard, Muriance", Mastered: false},
				{Type: "PhysAtk", Name: "DMG+10%", Found: "Clasping Claws", Mastered: false},
				{Type: "PhysAtk", Name: "DMG+20%", Found: "Hammerfist", Mastered: false},
				{Type: "PhysAtk", Name: "DMG+30%", Found: "Buzzsaw Arm", Mastered: false},
				{Type: "PhysAtk", Name: "Critical+20%", Found: "Buzzsaw Arm", Mastered: false},
				{Type: "PhysAtk", Name: "Accuracy+50%", Found: "Clasping Claws", Mastered: false},
				{Type: "PhysAtk", Name: "Quarry: SPIRIT", Found: "Wispstone", Mastered: false},
				{Type: "PhysAtk", Name: "Shield Break 10%", Found: "Hammerfist", Mastered: false},
				{Type: "PhysAtk", Name: "Degeneration 10%", Found: "Onyx", Mastered: false},
				{Type: "PhysAtk", Name: "Drain HP 10%", Found: "BloodOpal", Mastered: false},
				{Type: "PhysDef", Name: "DMG-10%", Found: "Copper Plating, SilverRing, GoldRing", Mastered: false},
				{Type: "PhysDef", Name: "DMG-20%", Found: "Steel Plating", Mastered: false},
				{Type: "PhysDef", Name: "DMG-30%", Found: "Titan Plating, Golden Gauntlet", Mastered: false},
				{Type: "PhysDef", Name: "DMG Soak 10", Found: "Pickaxe Pendant", Mastered: false},
				{Type: "PhysDef", Name: "DMG Soak 20", Found: "Skull Helm", Mastered: false},
				{Type: "PhysDef", Name: "Evasion 20%", Found: "Eclipse Amulet", Mastered: false},
				{Type: "MagAtk", Name: "M DMG+10%", Found: "Scoping Lens", Mastered: false},
				{Type: "MagAtk", Name: "M DMG+20%", Found: "Feather Crest", Mastered: false},
				{Type: "MagDef", Name: "M DMG-10%", Found: "Silver Circlet", Mastered: false},
				{Type: "MagDef", Name: "M DMG Soak 10", Found: "Elf Cap", Mastered: false},
				{Type: "MagDef", Name: "M FIRE-50%", Found: "FirePendant, Dragonblood Charm", Mastered: false},
				{Type: "MagDef", Name: "M WATER-50%", Found: "WaterPendant", Mastered: false},
				{Type: "MagDef", Name: "M AIR-50%", Found: "AirPendant", Mastered: false},
				{Type: "MagDef", Name: "M EARTH-50%", Found: "EarthPendant", Mastered: false},
				{Type: "MagDef", Name: "M DARK-50%", Found: "Black Hat", Mastered: false},
				{Type: "Passive", Name: "Mechanical body", Found: "Starting Skill", Mastered: true},
				{Type: "Passive", Name: "HP+10%", Found: "Copper Plating, Body Crystal", Mastered: false},
				{Type: "Passive", Name: "HP+20%", Found: "Steel Plating, Emerald Bangle", Mastered: false},
				{Type: "Passive", Name: "HP+30%", Found: "Titan Plating", Mastered: false},
				{Type: "Passive", Name: "MP+10%", Found: "Mind Crystal, Lapis Lily", Mastered: false},
				{Type: "Passive", Name: "MP+20%", Found: "Sapphire Bangle, SoulStone", Mastered: false},
				{Type: "Passive", Name: "Antibody", Found: "Snakestone, Viper's Eye", Mastered: false},
				{Type: "Passive", Name: "Loquacity", Found: "Sorcerer's Soul", Mastered: false},
				{Type: "Passive", Name: "Suppleness", Found: "Dragonblood Charm, Warlord's Soul", Mastered: false},
				{Type: "Passive", Name: "Insomnia", Found: "Cog Necklace, MoonstoneRing, Moonstone", Mastered: false},
				{Type: "Passive", Name: "Clarity", Found: "Amethyst, Amethyst Earring", Mastered: false},
				{Type: "Passive", Name: "Locomotion", Found: "Belt of Movement", Mastered: false},
				{Type: "Passive", Name: "Bright Eyes", Found: "OnyxRing, SolakianAmulet", Mastered: false},
				{Type: "Passive", Name: "Vim", Found: "Bonestone", Mastered: false},
				{Type: "Passive", Name: "STR+1", Found: "FireOpal", Mastered: false},
				{Type: "Passive", Name: "STR+2", Found: "Ruby", Mastered: false},
				{Type: "Passive", Name: "VIT+1", Found: "Jade", Mastered: false},
				{Type: "Passive", Name: "VIT+2", Found: "Emerald", Mastered: false},
				{Type: "Passive", Name: "SPR+1", Found: "Aquamarine", Mastered: false},
				{Type: "Passive", Name: "SPR+2", Found: "Sapphire", Mastered: false},
				{Type: "Passive", Name: "AGL+1", Found: "Topaz", Mastered: false},
				{Type: "Passive", Name: "AGL+2", Found: "Boots of Celerity", Mastered: false},
				{Type: "Passive", Name: "Resist AETHER", Found: "Turquoise", Mastered: false},
				{Type: "Passive", Name: "Rainbow Aura Lv.1", Found: "Rainbow Disc", Mastered: false},
				{Type: "Passive", Name: "SOS Regen", Found: "Kind Star", Mastered: false},
				{Type: "Passive", Name: "SOS Berserk", Found: "Horned Helm", Mastered: false},
				{Type: "Passive", Name: "EXP+20%", Found: "Candriathope", Mastered: false},
				{Type: "Passive", Name: "Double AP", Found: "EveningStar", Mastered: false},
				{Type: "Passive", Name: "Double Gold", Found: "Regal Crown", Mastered: false},
				{Type: "Passive", Name: "Loot Finder Lv.1", Found: "Lucky Coin", Mastered: false}
			]
		}
	}
}
